### ISSUE TITLE
When I add a sql_filter to a joined table, and that references a field in that same table, I have to include it in the metric query

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#10120]
### Description

How to (with local dev setup)
- Modify `payments` to include a `sql_filter` that references `orders`.`status`:

```yml
- name: payments
    description: This table has information about individual payments
    meta:
      joins:
        - join: orders
          sql_on: ${orders.order_id} = ${payments.order_id}
          type: inner -> IMPORTANT
          fields: [status, customer_id, unique_order_count] -> IMPORTANT
        - join: customers
          sql_on: ${customers.customer_id} = ${orders.customer_id}
      sql_filter: >
        ${orders.status} = ${lightdash.attributes.order_status} or ${lightdash.attributes.order_status} = 'ALL'
```

- Push changes to LD UI
- Create a chart that uses `payments` table
- See an error like:
```
Unrecognized name: orders at...
```
- Only when we add the field `status` we can run a successful query
- Now select the `status` dimension
- It works

### Solutions proposal

- be able to work out why this is the case: could we just ignore the error and include the field? or have a better error?
- fix the underlying problem:
1. User adds `sql_filter` to `orders`
2. They join `orders` to `payments`
3. The filter doesn't carry to `orders`
4. We handle that on the compiler/backend/cli, we are good to go

### What problem does this solve?

Builder's confidence
