### ISSUE TITLE
Lightdash crashes when using wrong dimension types

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1028]
### Describe the bug

If I set a dimension type to `Number` instead of `number` the UI crashes.

e.g.
```yaml
columns:
  - name: mycol
    meta:
      dimension:
        type: Number
```

### To Reproduce

Compile a Lightdash project with a dimension using `Number` type

### Expected behavior

A sensible error should be shown (or we make the type case insensitive)
