### ISSUE TITLE
Date grouping doesn't work as expected when dimension has no label

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#10348]
### Description

`label` seems to be required for timestamp-interval grouping. See steps

### Steps to Reproduce the Bug or Issue

Go to `tracks.yml`
Go to 
```
 - name: timestamp
```
Remove `label` and refresh dbt
See grouping off
<img width="309" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/2b983b3d-e297-490a-b2f5-a47f9431c8a4">

Re-add `label`
See grouping on

<img width="381" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/758f7433-9212-418e-9dbd-aa96a5d20467">

### Cloud or self-hosting

cloud

**Comment by TuringLovesDeathMetal** [comment]
@joaoviana what is the .yml that's causing this? 

In our tracks table in lightdash analytics,there is no `label` field, and the time intervals are working fine 🤔 

```yaml
     - name: timestamp
        description: Timestamp indicating when the event happened
        meta:
          dimension:
            type: timestamp
            time_intervals: ['RAW', 'SECOND', 'MINUTE', 'HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR']
```

**Comment by joaoviana** [comment]
Good point @TuringLovesDeathMetal, I believe it could be a `time_interval` that is affecting this grouping breaking:
https://github.com/lightdash/lightdash-analytics/pull/483. draft PR for us to test

And current local yml setup for `lightdash` repo

```yml
 - name: timestamp
        description: ""
        meta:
          dimension:
            label: Timestamp
            type: timestamp
            time_intervals:
              - RAW
              - MILLISECOND
              - SECOND
              - MINUTE
              - HOUR
              - DAY
              - DAY_OF_WEEK_INDEX
              - DAY_OF_WEEK_NAME
              - DAY_OF_MONTH_NUM
              - DAY_OF_YEAR_NUM
              - WEEK
              - WEEK_NUM
              - MONTH
              - MONTH_NUM
              - MONTH_NAME
              - QUARTER
              - QUARTER_NUM
              - QUARTER_NAME
              - YEAR
              - YEAR_NUM
              - HOUR_OF_DAY_NUM
              - MINUTE_OF_HOUR_NUM
```

If I remove `label` from the yml example above ^ it will replicate the bug
