### ISSUE TITLE
Multiple joins to the same table from a table

### ISSUE THREAD

**Issue by philcarr-tsl** [lightdash/lightdash#1034]
### Describe the bug

There appears to be no way to join to the same table more than once from a table. The logic currently means that if you join to the same table more than once only one of the occurrences shows in the UI and it is unknown without testing (and viewing the SQL) which one it has chosen. There is also no way of giving the join (as it is on the dbt model name) an alias to make it appear to the end user different. 

### To Reproduce

1. Create a "users table" with several users in it (Primary Keys: user_id)
2. Create an "orders table" with two Foreign Key's to the "users table" of "order_user_id" and "benefactor_user_id"
3. Put some test data in; where the users are different.  
4. Create appropriate dbt files with the lightdash join meta flourish to join the orders table to the users table twice.
5. Column available in the interface will be to one of them.

### Expected behavior

Ability to name the joins so that the end user knows they are going to be pulling in the details for the "orderer" or the "benefactor" 

### Screenshots or Loom video

Sorry don't have a worked example I can share here.

**Comment by TuringLovesDeathMetal** [comment]
Hey @philcarr-tsl - sorry for the delayed reply. This must have gotten skipped in my notifications and I just stumbled back on it now 👀 

This is definitely behaviour that we should support. I've just re-labelled this as a feature-request instead of a bug because I think if we were to treat it as a bug, we'd just tell you in the UI which of the join logic was used to join the repeated table. 

But as a feature request, I think the solution would be to actually support having the same table joined multiple times. 

So here's how I'd imagine it looking like in your model .yaml file:
```
models:
  - name: users
    meta:
      joins:
        - join: web_sessions
          label: "Power User Web Sessions"
          sql_on: ${web_sessions.user_id} = ${users.user_id} AND ${web_sessions.is_active}
        - join: web_sessions
          label: "Other User Web Sessions"
          sql_on: ${web_sessions.user_id} = ${users.user_id} AND ${web_sessions.other}
```

In the UI, you'd see the labels for the joined tables instead of their original names. 

If you didn't add labels, we'd add numbering by default to differentiate the joined tables (e.g. `Web Sessions 1` and `Web Sessions 2`)


Is there anything missing in there for you?
