### ISSUE TITLE
Define joins with dbt foreign key tests

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1040]
### Description: What is it?

Instead of using Lightdash syntax to specify join logic. For simple foreign keys, dbt tests could be used.

An example from the [dbt docs on tests](https://docs.getdbt.com/reference/resource-properties/tests#relationships)

```yaml
version: 2

models:
  - name: orders
    columns:
      - name: customer_id
        tests:
          - relationships:
              to: ref('customers')
              field: id
```

Context: https://lightdash.slack.com/archives/C02QP2UKYVC/p1639750521008100
