### ISSUE TITLE
Alias table name doesn't actually use alias in query generation

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#10534]
### Description

think i've found a bug. I've created two joins as such:
```
   meta:
      joins:
        - join: dim_date
          sql_on: date(${dim_date.calendar_date}) = date(${parent_onboarding_stage_conversion.stage_a_created_at})
          alias: Stage A Created At Date                
        - join: dim_date
          sql_on: date(${dim_date.calendar_date}) = date(${parent_onboarding_stage_conversion.stage_b_created_at})
          alias: Stage B Created At Date
```

lightdash compiles find and I get these two tables against my table in the console. But if i select Stage b created at date: Is current month, which is a field in dim_date, i get the following SQL being generated and an error:

```
SELECT
  "Stage B Created At Date".is_current_month AS "Stage B Created At Date_is_current_month"
FROM MYTUTOR.platform_users.parent_onboarding_stage_conversion AS "parent_onboarding_stage_conversion"
LEFT OUTER JOIN MYTUTOR.utilities.dim_date AS "Stage B Created At Date"
  ON date(("Stage A Created At Date".calendar_date)) = date((TO_TIMESTAMP_NTZ(CONVERT_TIMEZONE('UTC', "parent_onboarding_stage_conversion".stage_b_created_at))))

GROUP BY 1
ORDER BY "Stage B Created At Date_is_current_month"
LIMIT 500
```

as you can see, it's bringing stage A into there when it should be bringing stage B in.

### Steps to Reproduce the Bug or Issue

- create an alias for a joined table
- use the joined table in a query in Lightdash
- see an error in the table name (it's using the original name)

### Cloud or self-hosting

None
