### ISSUE TITLE
Filter value autocomplete not showing up for additional dimensions

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#10580]
### Description

The filter value autocomplete did not show anything when trying to add a filter to a chart, specifically for additional dimensions.

![CleanShot 2024-07-01 at 12 58 38@2x](https://github.com/lightdash/lightdash/assets/5532776/2ee1ff3e-ba33-4fcd-8c3f-15dcfd25403b)

### Steps to Reproduce the Bug or Issue

1. Create a dimension that is defined in SQL (example `.yml` below, the `item_profit_margin_tier` dimension is the one that causes the bug)
2. Create a chart or dashboard with the explore that includes that new dimension
3. Try to add a filter using the SQL-defined dimension
4. No values appear as options in filter

```yml
  - name: item_profit
    description: 'Profit made for the individual item.'
    meta:
      dimension:
        format: 'usd'
        group: ['product_details', 'item_details']
      additional_dimensions:
        item_profit_margin:
          type: number
          description: Item profit divided by item price
          sql: ${item_profit} / ${item_price}
        item_profit_margin_tier:
          type: string
          description: True if item has profit margin greater than 12%
          sql: |
            case 
              when ${item_profit_margin} < .08 then 'Low profit margin' 
              when ${item_profit_margin} > .12 then 'High profit margin'
              else 'Mid profit margin' end
```

This code is added to our internal demo site with this PR: https://github.com/lightdash/lightdash-demo-data-gardening/pull/13

### Cloud or self-hosting

None

**Comment by owlas** [comment]
Is this also happening for regular dimensions with the `sql` specified?

**Comment by jpetey75** [comment]
I just tested and it looks like the filter autocomplete does work for regular dimension defined with a `sql` option @owlas

**Comment by neo-angie-uesato** [comment]
Do you guys have an ETA for this issue?

**Comment by rephus** [comment]
I can replicate, we get an error when trying to get results from these fields 

![image](https://github.com/user-attachments/assets/1795e638-3da9-4c49-b409-1978eae66e10)

>         "message": "Model \"events\" has a metric reference: ${event_id} which matches no metric",

**Comment by rephus** [comment]
This also affects dimensions with custom sql like: 

```
      - name: another_dimension
        description: ""
        meta:
          dimension:
            type: string
            sql: ${event_id}  +1
 ```
