### ISSUE TITLE
Support metrics in underlying data

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#11138]
### Description

[Slack thread](https://getdbt.slack.com/archives/C026WJE4A69/p1723612303328639)

> Hi, I have a use-case in main chart i need to show the number of player scored more than x score as average. When I click on the count I need to show player wise average score instead.
My dbt schema looks like this now.
```
name: distinct_players
        meta:
          metrics:
            distinct_players:
              type: count_distinct
              sql: "players"
              show_underlying_values:
                - players
                - scores
```
> Then I use lightdash to count the distinct players with average score (custom metric) by adding the filter to custom metric im getting the data. But when i click the main chart im getting the scores for each game. How do i get the average score in "Show underlying data" place.
