### ISSUE TITLE
I want to be able to override the description on a joined table 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#11538]
### Description

Add a description meta tag on joined tables to override the description of that table. 

```
version: 2

models:
  - name: reporting_base_table
    description: 'Base table description'
    meta:
      label: 'Reporting Base Table'
      joins:
        - join: joined_table
          label: 'Joined Table'
          sql_on:
            ${reporting_base_table.id} =
            ${joined_table.foreign_id}
          description: "Description over-ride that would be used in the LD UI for this join"

  - name: joined_table
    description: 'Joined table description -- this would be overwritten if the table is joined to something else and has a different description configured'
```
