### ISSUE TITLE
`lightdash preview` errors when there are variables used in my profiles.yml

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#11695]
### Description

When running dbt, I don't need to pass variables for templated portions of profiles.yml unless I am using a target that has a templated value. However, for lightdash preview it seems like all variables for all targets need to be provided in order to deem the profiles.yml as valid - even for the profiles that I'm not actively using. Is this intended?

As a specific example, this is the profiles.yml. ci_dataset is a string containing the PR number used for CI:

```yaml
main:
  outputs:
    dev:
      type: bigquery
      method: oauth
      dataset: default
      threads: 1
      location: EU
    prod:
      type: bigquery
      method: oauth
      dataset: default
      threads: 4
      location: EU
    ci:
      type: bigquery
      project: my-ci-project
      method: oauth
      dataset: "{{ var('ci_dataset') }}"
      threads: 1
      location: EU
  target: dev
```

lightdash preview --target dev throws an SyntaxError: Unexpected token '/', "/opt/homeb"... is not valid JSON error related to the ci target, which persists even if the ci target is commented out. If I remove the ci target entirely then lightdash preview --target dev works as expected. I was expecting to be able to provide a target, without vars needed for unrelated targets, similar to how I can with dbt.
