### ISSUE TITLE
time_intervals property is not working correctly on Additional dimensions 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#11716]
### Description

I created an additional dimension of a date , I used time_intervals: 'OFF' and it is creating 2 dimensions, one without time intervals, and another one with the default interval, there should be only 1 . 

Also adding only `['YEAR']` doesn't work as expected

### Steps to Reproduce the Bug or Issue

1. add this to the yml

```
      - name: created
        description: Timestamp (UTC) when customer was created
        meta:
          additional_dimensions:
            created_year:
              type: date
              time_intervals: 'OFF'
              label: "Enrollment Season Year (Date)"
              sql: to_date(created || '-01-01', 'YYYY-MM-DD')
```

2. Refresh dbt
3. Get 2 dimensions

![image](https://github.com/user-attachments/assets/1f86f9f7-00a9-40c7-b6de-e1e888fb466b)

### Cloud or self-hosting

None
