### ISSUE TITLE
`"Snowflake error: A password must be specified"` in CLI after updating CLI

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#11954]
### Description

After updating to npm cli@0.1302.4, the user encountered a “Snowflake error: A password must be specified” when running queries in developer preview mode. The same error occurs in the terminal when using Lightdash commands. Rolling back to npm cli@0.1243.0 resolves the terminal error, but the UI (developer preview) still shows the issue.

### Steps to Reproduce the Bug or Issue

1.	Update to npm cli@0.1302.4.
2.	Run any Lightdash command in the terminal.
3.	Observe the Snowflake error.
4.	Roll back to npm cli@0.1243.0.
5.	Reproduce the error in the UI (after preview deploy).

### Cloud or self-hosting

None

**Comment by IrakliJani** [comment]
`dbt debug` connection succeeds

profiles.yml example:

(note that it has no password field but it uses private key authentication)

```
default:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: <account_name>
      user: <user_name>
      private_key_path: <private_key_path>
      private_key_passphrase: <private_key_passphrase>
      role: TRANSFORM
      database: dbt
      warehouse: elt_xs
      schema: dbt
      threads: 8
      client_session_keep_alive: False
```
