### ISSUE TITLE
my `number` metric type is showing the incorrect total value in a pivot table. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12047]
### Description

Slack thread here: https://lightdash.slack.com/archives/C04FQQU4RL7/p1729681989919299

If I have a `number` metric type defined like this:

```yaml
- name: revenue
    meta:
      metrics:
        total_revenue:
          type: sum
- name: cost
    meta:
      metrics:
        total_cost:
          type: sum
        total_percent_profit: # this is my number metric!
          type: number
          sql: 100 * ${total_revenue}/${total_cost}
```

In my unpivoted table, the column total shows me the correct answer (it takes `SUM(total_revenue across column)/SUM(total_cost across column)`). But, when I pivot the data, it sums each row (`SUM(total_revenue / total_cost)`). This gives me the wrong answer. 

Either we should remove these metric types (number) or we should make them work properly in pivoted tables. I think that if we know the metric type = `number`, then we should just calculate the row total based on the other metric row totals. This would only work for `number` metric types that are built from other metrics that are sums or counts.
