### ISSUE TITLE
Collapse and truncate string metrics with long values

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#12084]
### Description

There are multiple UI issues when handling a string metric with long values.

We should disable totals for string metrics and truncate the value in the other places.

Example of problems:
Total cell, cell menu, drill modal, etc

<img width="1345" alt="Screenshot 2024-10-24 at 15 01 57" src="https://github.com/user-attachments/assets/b310983d-fd0e-45f3-8d71-1a3ebb49a552">
<img width="1765" alt="Screenshot 2024-10-24 at 15 38 34" src="https://github.com/user-attachments/assets/d0d6596a-e9b7-40bd-904d-deb15e351f02">
<img width="475" alt="Screenshot 2024-10-24 at 15 40 13" src="https://github.com/user-attachments/assets/33907836-8c1e-42e4-b358-5f827f5d726c">

### Steps to Reproduce the Bug or Issue

Add the following string metric `test_agg`:

```
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
        meta:
          metrics:
            unique_customer_count:
              type: count_distinct
              label: Unique customer count
              description: Total number of customers
            test_agg:
              type: string
              sql: "STRING_AGG(first_name || ' ' || last_name,',' ORDER BY first_name, last_name)"
```

### Cloud or self-hosting

cloud
