### ISSUE TITLE
Joined models are not compiling because of additional dimension reference

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12157]
### Description

- they’ve created an additional dimension in model A that uses a field from a joined model (call it model B)
- the model A compiles :white_check_mark:
- the model B is also joined to model A (in the model B’s .yml file).
- model B fails compiling :no_good: because it complains about the additional dimension (from model A).

### Steps to Reproduce the Bug or Issue

see above (and slack thread here: https://lightdash.slack.com/archives/C053ESBT36V/p1730208616077569?thread_ts=1730203374.098399&cid=C053ESBT36V)

### Cloud or self-hosting

None

**Comment by rephus** [comment]
Nothing to fix, it was a bad configuration (empty 

```
    - name: field_1 
      meta: 
        dimension: 
              hidden: true 
        additional_dimensions:  <--- this was the empty line that was causing the issue
    - name: field 2
```
