### ISSUE TITLE
Explore view broken for tables with identical dimension and metric names

### ISSUE THREAD

**Issue by nkotlyarov** [lightdash/lightdash#1215]
Explore probably breaks when the metric has the same definition as a column!

### To Reproduce

YAML example:
```
version: 2
models:
  - name: stats_daily_projects
    description: "Legacy basic daily metrics"
    columns:
      - name: "report_date"
      - name: "project_id"
        meta:
          metrics:
            projects_count:
              type: "count_distinct"
      - name: "total_requests"
        meta:
          metrics:
            total_requests:
              type: "sum"

```

![image](https://user-images.githubusercontent.com/5070583/150803578-6ea1f557-bb02-4e76-9584-773943cec0f3.png)
