### ISSUE TITLE
I want to add `group labels` for my joined tables

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12153]
### Description

I have a view with a lot of joined tables to it (e.g. 10+ joined tables). I want to be able to group those joined tables in the sidebar so that they're easier to navigate. 

We could use `group_details` like we do for metrics/dimensions...but this feels a bit weird. https://docs.lightdash.com/references/dimensions#groups

I'm wondering if we should use `group_label` in the model.yml? like this:

```
version: 2
models:
  - name: organizations_daily
    meta:
      joins:
        - join: slurpee_kpi_metric_targets
          group_label: 'slurpees'
          sql_on: >-
            ${slurpee_kpi_metric_targets_joined_week.week_commencing} =
            ${organizations_daily.week}
        - join: slurpee_kpi_metric_targets
          group_label: 'slurpees'
          sql_on: >-
            ${slurpee_kpi_metric_targets_joined_org_created_week.week_commencing}
            = ${organizations_daily.organization_created_week}
```
