### ISSUE TITLE
There's a way to add `tags` to the fields in my .yml files

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12258]
### Description

There's a new parameter called `tags` in the .yml files for metrics.

### Acceptance criteria

```yaml
    columns:
      - name: id
        description: The primary key for this table
        meta:
          dimension:
            tags: ['i-am-a-tag', 'pii-data']
          metrics:
            page_view_count:
              type: count_distinct
              tags: ['katie-is-the-best', 'irakli-is-cool', 'marketing']
           another_metric:
             type: sum
             tags: one-lonely-tag
```
 
- [ ] I can add `tags` as a parameter to my metrics and dimensions in my .yml files. 
- [ ] I can add many tags as a list
- [ ] I can add a single tag
