### ISSUE TITLE
additional dimensions that are timestamp and date is picking up description from the `meta dimension`

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12257]
### Description

see slack thread here: https://lightdash.slack.com/archives/C06PAQCH932/p1730820923271739?thread_ts=1730742625.372169&cid=C06PAQCH932

If you have a column name and add a meta description, then you add an additional dimension, the description fo the additional dimension is the meta description name (not the additional dimension's description). This seems to only be happening for date + timestamp types. 

E.g. if I have .yml like this: 

```yaml
columns:
      - name: id
        description: The primary key for this table
        meta:
          dimension:
            type: string
            description: my special description
          additional_dimensions:
              my_date_dimension:
                type: date
                sql: blah
                description: this is the description I actually want
```

then for `my_date_dimension`, it will have the description `my special description`. 

### Steps to Reproduce the Bug or Issue

1. add a `meta: dimension: description` to your column (see above example)
2. add a date additional dimension with a description
3. see that the additional dimension description is wrong. 

### Cloud or self-hosting

None
