### ISSUE TITLE
Hidden flag fails on date type additional dimensions

### ISSUE THREAD

**Issue by jpetey75** [lightdash/lightdash#12349]
### Description

When you have a date type in an additional dimension, then try to use `hidden: true` it will fail and still show up, unless you also include `time_intervals: OFF`.

### Steps to Reproduce the Bug or Issue

Given YAML definition like this:

```yml
    columns:
      - name: report_date
        meta:
          dimension:
            label: Report Date
            type: date
            time_intervals: ['DAY', 'DAY_OF_YEAR_NUM', 'WEEK', 'MONTH', 'MONTH_NUM', 'QUARTER', 'YEAR', 'YEAR_NUM']
            group_label: Report Date
          additional_dimensions:
            report_week:
              type: date
              hidden: true
              sql: "DATE_TRUNC('week', ${report_date})"
```

The `report_week` dimension will not be hidden in the query builder unless you update to this (added `time_intervals: OFF` flag):

```yml
    columns:
      - name: report_date
        meta:
          dimension:
            label: Report Date
            type: date
            time_intervals: ['DAY', 'DAY_OF_YEAR_NUM', 'WEEK', 'MONTH', 'MONTH_NUM', 'QUARTER', 'YEAR', 'YEAR_NUM']
            group_label: Report Date
          additional_dimensions:
            report_week:
              type: date
              hidden: true
              time_intervals: OFF
              sql: "DATE_TRUNC('week', ${report_date})"
```

But the `hidden` flag should work regardless.

### Cloud or self-hosting

cloud
