### ISSUE TITLE
Upper case DBT column names displayed with gaps

### ISSUE THREAD

**Issue by gary-beautypie** [lightdash/lightdash#1278]
### Describe the bug

When using upper case column names in my DBT schema files, I get big gaps in the column names on the tables in Lightdash.

### To Reproduce

Example schema.yml
```
version: 2

models:
  - name: dim_table
    description: Moo

    columns:
      - name: DESCRIPTION
        description: Desc
      - name: CANCELLED_AT
        description: When it was cancelled
```

Sync models in Lightdash

### Expected behavior

To display as CANCELLED_AT or CANCELLED AT if underscores are intentionally removed

### Screenshots or Loom video

What appears in Lightdash:

![Screenshot 2022-02-02 at 16 01 52](https://user-images.githubusercontent.com/71257526/152191723-ccc34c86-7cdb-43b1-ba0b-4b4733862a5a.png)
