### ISSUE TITLE
lightdash generate suggests removal of non-materialised columns from yml, even if the column is calculated with sql

### ISSUE THREAD

**Issue by mhawkins-runa** [lightdash/lightdash#12827]
### Description

When running `lightdash generate`, it asks if you want to remove any columns if they're not present in the model sql. This is usually helpful, and I generally answer "Yes" without thinking about it.

The problem is that, if you have a column that (for example) doesn't appear in the sql model, but does appear in the yml and is created using `meta.dimension.sql`, it still suggests removing the column. If we have defined the column in the yml using sql, the default assumption should be that this was done intentionally (e.g. to make a certain dimension accessed via a yml-defined join easier for end users to find). If `lightdash generate` suggests removing such columns, there is a danger that we will remove them without thinking. In my opinion, `lightdash generate` should only suggest removing columns where no `sql` attribute is specified.
![image](https://github.com/user-attachments/assets/e9b058a6-9260-43f5-a78b-40f9bca4dedc)
![image](https://github.com/user-attachments/assets/c3e5e508-85ed-4a73-a9f6-126bf9ba0ad9)

### Steps to Reproduce the Bug or Issue

1. In a fact table, remove a dimension from the sql model, but not from the yml file
2. Create a join in the yml file to the relevant dimension table
3. Amend the column definition for the removed dimension in the yml file to source it from the joined dimension table using the `sql` attribute
4. Run `lightdash generate`

### version

v0.1410.2

### Cloud or self-hosting

cloud

**Comment by TuringLovesDeathMetal** [comment]
👋 Hey @mhawkins-runa 

The `lightdash generate` command compares all of your columns to the columns in your data warehouse. So, I'm not surprised that it's triggering this error. 

What if you try adding the column as an `additional dimension` instead of creating a `column`? 

I wonder if actually, we should add `additional dimension` as an option to define at the model level, then maybe that would help with your use case? Instead of trying to define columns in dbt's .yml that aren't actually columns in your data model. 

So, something like:

```
version: 2

models:
  - name: sales_stats
    meta:
      joins:
        - join: web_sessions
          sql_on: ${web_sessions.date} = ${sales_stats.date}
      additional_dimensions:
        days_to_first_query_run:
          type: number
          description: 'Number of days between a user being created and their first query run.'
          sql: ${first_query_date} - ${created_date}
```
