### ISSUE TITLE
metric filter is concatenating filter values instead of separating them in a list

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#12882]
### Description

![image](https://github.com/user-attachments/assets/d0acadb6-b244-4c7e-8cdb-81af0c649727)

![image](https://github.com/user-attachments/assets/4d24f694-74f0-4cfb-8096-be8df7284ba8)

https://docs.lightdash.com/references/metrics#filters:~:text=To%20filter%20a%20field%20by%20a%20set%20of%20given%20values%20you%20can%20supply%20them%20as%20an%20array%20for%20that%20field.%20For%20example%2C%20if%20you%20wanted%20to%20filter%20for%20orders%20with%20order%20status%20completed%20or%20shipped%20you%20should%20write%20the%20metric%20like%3A

### Steps to Reproduce the Bug or Issue

1. create a filter on a metric (might have to be a metric at the model-level)
2. add another filter value
3. try using the metric
4. see that the values are not comma-separated, they appear like one string with a comma between them

### Cloud or self-hosting

None

**Comment by magnew** [comment]
I cannot repro this with:

1. Filters on the model
```
- name: orders
    meta:
      joins:
        - join: customers
          sql_on: ${customers.customer_id} = ${orders.customer_id}
      metrics:
        total_revenue:
          sql: ${orders.amount}
          type: sum
          filters:
            - status:
              - completed
              - return_pending
```
2. Filters on metrics
`under columns -> column -> meta -> metrics -> metric -> filters
3. With Snowflake as a warehouse specifically (as the customer has)

Any other ideas?
