### ISSUE TITLE
I want to be able to reference other fields from my results table in my liquid formatting.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#13486]
### Description

I want to be able to reference other fields using liquid formatting. 

### Acceptance criteria

- I can reference other fields from the same row in my results table, using html liquid formatting. 
- e.g. 
```yaml
      - name: edition
        description: ""
        meta:
          dimension:
            type: string
            html: <a href="${website.url._value}" target="_blank">${value}</a>
```
- The format to reference other fields is `${table_name.field_name._formatting_value_liquid}`
