### ISSUE TITLE
add custom formatting for metrics to .yml metrics

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#13487]
### Description

Right now, we have a lot of formatting options for custom metrics in the UI. But, we don't match these formatting options in the .yml. This means that we can only have write-back for unformatted custom metrics. To be able to support custom metrics write back, we need to be able to add custom formatting for metrics written in .yml (then we can translate the formatting from custom metrics)

### Acceptance criteria

- If there is `format` already applied, then we can check if it's one of the 5-ish format options we have. And if it isn't, we can trreat it like the Excel formula. 
- delete teh docs on the old `format` options (maybe) - add something to say this is an old way. (legacy formatting options page? so that people can still have docs if they're using the old formatting option).

#### Option 1 (we're picking this one)

- we create a totally custom format option which allows you to add formatting based on Excel-type formatting. 
- this means that for custom metrics that are formatted, we translate these to the excel-type formatting and inject this into teh SQL under the `format` option. 
- https://customformats.com/
- e.g. a percentage formatted with 0 rounding would look like this: `#,##0%`
- https://www.npmjs.com/package/numfmt

#### Option 2:

- we add new parameters that can be applied for numeric metrics that can be formatted: sum, average, count, count_distinct, min (for numeric types), max (for numeric types), median
- The `format` value can take on three values: `currency`, `percent`, `number`
- for `currency`, there are four sub-parameters:
```yaml
metrics:
  type: sum
  format: currency
    currency: usd (or gbp, eur, jpy, chf, dkk)
    round: 0
    compact: thousands (or K), millions, M, billions, B, trillions, T
    separator: "100,000.00" (or "100 000.00" or "100.000,00" or "100000.00")
```
- for `percent` there are two sub-parameters:
```yaml
metrics:
  type: number
  format: percent
    round: 0
    separator: "100,000.00" (or "100 000.00" or "100.000,00" or "100000.00")
```
- for `number` there are five sub-parameters:
```yaml
metrics:
  type: sum
  format: number
    round: 0
    compact: thousands (or K), millions, M, billions, B, trillions, T
    separator: "100,000.00" (or "100 000.00" or "100.000,00" or "100000.00")
    prefix: "any_value_here"
    suffix: "any_value_here"
```
