### ISSUE TITLE
I want to be able to format my fields using liquid.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#13485]
### Description

I want to be able to use liquid ([like we have for links](https://docs.lightdash.com/references/dimensions#liquid-templating)), but to format how the values in my results table look. 

### Acceptance criteria

- For dimensions, there is a parameter called `html` that I can use in my dimension configuration in the .yml
```yaml
      - name: edition
        description: ""
        meta:
          dimension:
            type: string
            html: <img src="https://www.lightdash.com/product_images/{{ value }}.jpg" />
```

- I can add html liquid formatting to this parameter and my field will appear with this formatting in my results table.
