### ISSUE TITLE
create translation between custom metric formatting (in the UI) and custom formats for .yml metrics

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#13619]
### Description

[Now that we have a `custom` format option for YAML metrics](https://github.com/lightdash/lightdash/issues/13487), we need to build a translator between teh formatting for custom metrics written in the UI and these custom format expressions. 

### Acceptance criteria

- [ ] for custom metrics with formatting, if you try to do `write back to dbt`, we add a `format` using custom formatting expressions that match the format the user set up in the UI. 
- [ ] the YAML should look like:

```yaml
        meta:
          metrics:
            comments_created_lightdash_team_num_total:
              label: Comments created Lightdash team num total
              type: sum
              format: '##.00'
```
