### ISSUE TITLE
I would like to categorise all metrics given a directory in `lightdash.config.yml`

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#13662]
### Description

After working on https://github.com/lightdash/lightdash/issues/13400, we developed: 
- definition of categories in `lightdash.config.yml`
- referencing those same categories in models

From the internal proposal doc: https://www.notion.so/lightdash/Proposals-17da63207a7a80ac953dd2da5f9c388d?pvs=4#17da63207a7a8068afb0d74674e2ff0f we know that allowing the specification of directories would be beneficial to users.

So it would go like so: 

```yml
spotlight:
  default_visibility: hide # Optional, defaults to "show"

  categories:
    core:
      label: "Core Metrics"
      color: blue
    experimental:
      label: "Experimental Metrics"
      color: orange

  directories:
    - presentation_core_folder:
        categories: 
          - core
          - experimental
```

all metrics that live in `presentation_core_folder` will have their metrics categorised with `core` and `experimental`.

To address: 
- [ ] allow definition of directories and suggest users to define them as a relative path from this file to the folder/directory
- [ ] provide clear errors when directories are wrong
- [ ] track if `directories` are defined
- [ ] add validation if the categories referenced in directories are not initialised in the categories section above in the same file
- [ ] what happens when directories are moved in the folder structure? 
- [ ] add docs 
- [ ] add headway update

### What problem does this solve?

Speeds up categorisation dev workflow
