### ISSUE TITLE
Project-level currency configuration

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#13684]
## Problem
Teams need to maintain multiple Lightdash instances with different currencies while using shared dbt models. Current currency formatting requires hardcoding symbols/formatting per metric, leading to duplication across projects.

Proposed Solution

1. Configuration Structure

`lightdash.config.yaml`

```yml
formatting:
  currency:
    code: '{{var('currency')}}'
    decimal_places: 2 # optional
```

`dbt_project.yaml`

```yml
vars:
  - currency: 'usd' # gbp, etc
```

in a `model.yml`:

```yml
columns:
  - name: revenue
    meta:
      dimension:
        currency/format: 'var(currency)' // since we allow other types, like the ones in the docs
```

Implementation Requirements
1. Currency configuration parsing from lightdash.config.yml (see DbtBaseProjectAdapter.ts)
2. Variable substitution in metric/dimension formatting (see translator.ts )
3. Allow other options' overrides, like units, round, etc

Acceptance Criteria
[ ] Currency code resolution from dbt variables
[ ] Automatic value division when unit=cents
[ ] Decimal places respect configuration
[ ] Variable changes propagate without model modifications

### Example Use Cases

US Dollars (Cents)

```yml
# dbt_project.yaml
vars:
  currency: usd

# lightdash.config.yaml
formatting:
  currency:
    unit: cents
```
Stored value: 1500 → Displays as $15.00

Japanese Yen

```yml
# dbt_project.yaml 
vars:
  currency: jpy

# lightdash.config.yaml
formatting:
  currency:
    unit: null
    decimal_places: 0

```

Stored value: 1500 → Displays as ¥1,500
