### ISSUE TITLE
I want better sort options for Pivot tables

### ISSUE THREAD

**Issue by oli-rmsy** [lightdash/lightdash#13754]
### Description

When using pivot columns in a table the chart should sort the values of the pivot column and display the columns accordingly

When faced with a sparse dataset, it can be impossible to sort Pivot tables in a logical way. I have created an [example](https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/saved/286c3479-eee9-4658-89ef-9139838f78fe/view) with a virtual view in our internal Lightdash instance.

![Image](https://github.com/user-attachments/assets/f55c2ed8-2d54-45da-869a-37e72383680e)

Users should be able to better specify the sort order of their columns - the easiest way to achieve this is likely to provide sorting options in the pivot table config.

### What problem does this solve?

Pivot tables are not useful unless the sorting and structure is logical.

**Comment by benjdworx** [comment]
There also exists a more complicated case where I want a pivot column to be a string but I want that pivot column sorted by a separate numerical column.

Consider this SQL `pivot_date.sql`:
```sql
SELECT id, date::DATE
FROM (
    VALUES 
    (1, '2025-01-06'), (2, '2025-01-06'), (3, '2025-01-07'), (4, '2025-01-07'), (5, '2025-01-08'),
    (6, '2025-01-08'), (7, '2025-01-08'), (8, '2025-01-09'), (9, '2025-01-09'), (10, '2025-01-10'),
    (11, '2025-01-10'), (12, '2025-01-11'), (13, '2025-01-11'), (14, '2025-01-12'), (15, '2025-01-12'),
    (16, '2025-01-12'), (17, '2025-01-13'), (18, '2025-01-13'), (19, '2025-01-14'), (20, '2025-01-14'),
    (21, '2025-01-15'), (22, '2025-01-15'), (23, '2025-01-15'), (24, '2025-01-16'), (25, '2025-01-16'),
    (26, '2025-01-17'), (27, '2025-01-17'), (28, '2025-01-18'), (29, '2025-01-18'), (30, '2025-01-19'),
    (31, '2025-01-19'), (32, '2025-01-20'), (33, '2025-01-20'), (34, '2025-01-21'), (35, '2025-01-21'),
    (36, '2025-01-21'), (37, '2025-01-22'), (38, '2025-01-22'), (39, '2025-01-23'), (40, '2025-01-23'),
    (41, '2025-01-24'), (42, '2025-01-24'), (43, '2025-01-24'), (44, '2025-01-25'), (45, '2025-01-25'),
    (46, '2025-01-26'), (47, '2025-01-26'), (48, '2025-01-27'), (49, '2025-01-27'), (50, '2025-01-27'),
    (51, '2025-01-28'), (52, '2025-01-28'), (53, '2025-01-29'), (54, '2025-01-29'), (55, '2025-01-30'),
    (56, '2025-01-30'), (57, '2025-01-31'), (58, '2025-01-31'), (59, '2025-02-01'), (60, '2025-02-01'),
    (61, '2025-01-06'), (62, '2025-01-06'), (63, '2025-01-08'), (64, '2025-01-08'), (65, '2025-01-09'),
    (66, '2025-01-10'), (67, '2025-01-11'), (68, '2025-01-12'), (69, '2025-01-13'), (70, '2025-01-14'),
    (71, '2025-01-15'), (72, '2025-01-16'), (73, '2025-01-17'), (74, '2025-01-18'), (75, '2025-01-19'),
    (76, '2025-01-20'), (77, '2025-01-21'), (78, '2025-01-22'), (79, '2025-01-23'), (80, '2025-01-24'),
    (81, '2025-01-25'), (82, '2025-01-26'), (83, '2025-01-27'), (84, '2025-01-28'), (85, '2025-01-29'),
    (86, '2025-01-30'), (87, '2025-01-31'), (88, '2025-02-01'), (89, '2025-02-01'), (90, '2025-02-01'),
    (91, '2025-01-10'), (92, '2025-01-15'), (93, '2025-01-20'), (94, '2025-01-25'), (95, '2025-01-30'),
    (96, '2025-01-06'), (97, '2025-01-14'), (98, '2025-01-22'), (99, '2025-01-29'), (100, '2025-02-01')
) AS t(id, date)
```

and this schema:
```yml
models:
  - name: pivot_date
    columns:
      - name: id
        data_type: number
        meta:
          metrics:
            total_count:
              type: count
      - name: date
        data_type: date
        meta:
          dimension:
            type: date
            time_intervals: ['DAY', 'WEEK', 'MONTH', 'YEAR', 'WEEK_NUM', 'DAY_OF_WEEK_INDEX', 'DAY_OF_WEEK_NAME']
          additional_dimensions:
            day_of_week_short:
              type: string
              sql: TO_CHAR(${date}, 'Dy')
```

In order to get a pivot column on the weekday name I need to include the day of week index. I want to hide this pivot column though (or be able to indicate that I want to sort by the index but not display it)

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/2278074f-ab17-4d28-b519-a26470397315" />

**Comment by benjdworx** [comment]
There are certain situations where we need to use a separate query for the pivot columns. For example when we have sparse dates:

Using `pivot_dates.sql`
```sql
 SELECT t.id,
    t.date::date AS date
   FROM ( VALUES (1,'2025-01-06'), (21,'2025-01-15'), (22,'2025-01-15'), (23,'2025-01-15'), (29,'2025-01-18'), (30,'2025-01-19'), 
   (31,'2025-01-19'), (32,'2025-01-20'), (59,'2025-02-01'), (60,'2025-02-01'), (81,'2025-01-25'), (82,'2025-01-26'), 
   (83,'2025-01-27'), (84,'2025-01-28'), (85,'2025-01-29'), (86,'2025-01-30'), (87,'2025-01-31'), (88,'2025-02-01'), 
   (89,'2025-02-01'), (90,'2025-02-01'), (96,'2025-01-06'), (97,'2025-01-14'), (98,'2025-01-22'), (99,'2025-01-29'), 
   (100,'2025-02-01')) t(id, date);
```

and the schema:
```yaml
models:
  - name: pivot_date
    columns:
      - name: id
        data_type: number
        meta:
          metrics:
            total_count:
              type: count
      - name: date
        data_type: date
        meta:
          dimension:
            type: date
            time_intervals: ['DAY', 'WEEK', 'MONTH', 'YEAR', 'WEEK_NUM', 'DAY_OF_WEEK_INDEX', 'DAY_OF_WEEK_NAME']
          additional_dimensions:
            day_of_week_short:
              type: string
              sql: TO_CHAR(${date}, 'Dy')
```

We now get a very messed up date order:

<img width="1727" alt="Image" src="https://github.com/user-attachments/assets/878ae831-dedd-4001-8b86-8f01cf0a9225" />


What's even worse is that applying filters can change the column order:

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/4b58f01a-17fa-441c-9d8f-2df599af3dbe" />
