### ISSUE TITLE
I want to be able to define `additional dimensions` at the model level

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#13817]
### Description

Right now, you can only define additional dimensions at a dimension-level. Instead, I want to be able to define additional dimensions at a model-level. 

This is so that we can write back custom dimensions as additional dimensions and write them to a model-level (instead of needing to guess the dimension to map them to). This is important for the custom SQL custom dimension types. 

### Acceptance criteria

- [ ] you can add additional dimensions to the model YAML, like:

```yaml
version: 2
models:
  - name: stripe_subscriptions
    meta:
      joins:
        - join: organizations
          sql_on: >-
            ${stripe_subscriptions.lightdash_organization_id} =
            ${organizations.organization_id}
     dimensions:  # these are called `dimensions` at the model level. But `additional dimensions` at teh dimension-level. This is because metrics are called `metrics` at the model-level. It's weird to call them `additional dimensions` if there are no `dimensions` to begin with. 
      my_custom_sql_dimension:
        type: number
        sql: blah blah blah
      another_custom_sql_dimension:
        type: string
        sql: blah blah blah

    columns:
      - name: subscription_id
        meta:
          dimension:
            additional_dimensions:
              my_bin:
                type: string
                sql: bin logic SQL
```

- [ ] add this to the `dimensions` reference doc.
