### ISSUE TITLE
You should be able to set metrics/dimensions to be rounded by default in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1390]
### Description: What is it?

In the .yml file, when you define metrics + dimensions, there should be a meta tag that lets you round the metrics/dimensions to a default value for numeric values. 

This is sort of related to this issue: 
https://github.com/lightdash/lightdash/issues/372

### Problem: What problem does this solve?

Right now, if you want to round a numeric value, you have to create a table calculation for it. If you're a non-power-user, it's unlikely that you'll know how to do that. So you'll get some really ugly numbers appearing in visualizations for people (especially for metrics that are using custom SQL where you're dividing two numbers, or average metric types)

### Success: How will we know if we’ve solved this problem?

Users are able to set the decimal point accuracy for their metrics when they're defining their metrics.

### Audience: Who are we building this for?

Data builders: specifically, the people defining the Lightdash metrics in your dbt project. 

### What: Roughly, what does this look like in the product?

E.g. 
```
columns:
  name: revenue
  meta: 
    metrics:
      total_revenue:
        type: sum
        round: 2
```

If I added this metric in the UI, the column would now look like:

40.00
567.00
etc.

**Comment by PriPatel** [comment]
Yes! 100% - especially for big numbers in dashboards!

**Comment by TuringLovesDeathMetal** [comment]
^totally - I think you should be able to also adjust the rounding in the chart config :) but that's a separate issue ;)

**Comment by colin-nayuta** [comment]
+1 for this one
related to how to format the number in the front end

and now
what i am doing is.....

```
        meta:
          metrics:
            total_spend_eur:
              type: number
              sql: round(sum(spend))
```

instead of this

```
        meta:
          metrics:
            total_spend_eur:
              type: sum
              round: 0
```
