### ISSUE TITLE
Remove tab uuids on dashboards as code

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#13996]
CUrrently, dashboards as code work well with tabs, you can download a dashboard with tabs in a project, and upload it on a different project, despite using uuids, they work across projects. 

Still, uuids don't look great on content as code, so it would be nice if we can replace it with something else (perhaps just the tab name) , or a dynamic tab slug. 

Sample

```
name: dashboard with filters
description: ""
updatedAt: "2025-03-10T10:19:00.175Z"
tiles:
  - x: 0
    "y": 0
    h: 9
    w: 15
    tabUuid: 9b898984-69a1-4ca0-ae8c-24279b0e60ed
    type: saved_chart
    properties:
      title: ""
      hideTitle: false
      chartSlug: how-much-revenue-do-we-have-per-payment-method-each-month
  - x: 0
    "y": 2
    h: 9
    w: 15
    tabUuid: cc35b013-bac5-4fcb-b837-0640bc7822b2
    type: saved_chart
    properties:
      title: ""
      hideTitle: false
      chartSlug: how-do-payment-methods-vary-across-different-amount-ranges
  - x: 0
    "y": 0
    h: 9
    w: 15
    tabUuid: cc35b013-bac5-4fcb-b837-0640bc7822b2
    type: saved_chart
    properties:
      title: ""
      hideTitle: false
      chartSlug: what-s-our-total-revenue-to-date
  - x: 16
    "y": 1
    h: 9
    w: 15
    tabUuid: 9b898984-69a1-4ca0-ae8c-24279b0e60ed
    type: saved_chart
    properties:
      title: ""
      hideTitle: false
      chartSlug: how-many-users-were-created-each-month
  - x: 16
    "y": 1
    h: 9
    w: 15
    tabUuid: cc35b013-bac5-4fcb-b837-0640bc7822b2
    type: saved_chart
    properties:
      title: ""
      hideTitle: false
      chartSlug: what-s-the-average-spend-per-customer
filters:
  metrics: []
  dimensions:
    - id: 1dae2340-85a9-4ee4-81ed-593a57aedc86
      target:
        fieldId: customers_created_month
        fieldName: created_month
        tableName: customers
      values:
        - 2017-01
      disabled: false
      operator: equals
      tileTargets:
        e841b9ba-b776-4d11-b97f-638bb0ac065f: false
    - id: ebbc36bb-25f7-4625-aef1-0ab18a7e56eb
      target:
        fieldId: customers_created_month
        fieldName: created_month
        tableName: customers
      values:
        - 2017-02
      disabled: false
      operator: equals
      tileTargets:
        0fa4fade-81f1-4c4f-8230-b082b4edc94d: false
        6a6a8930-f29a-4f9e-8cfc-1be6b64f5e11: false
        74ad6e9d-8e39-4e0c-93fb-b519286b9f89: false
        e9b36fc7-223c-4c1d-a368-51353c6a238b: false
  tableCalculations: []
tabs:
  - name: Tab 1
    uuid: 9b898984-69a1-4ca0-ae8c-24279b0e60ed
    order: 0
  - name: new tab
    uuid: cc35b013-bac5-4fcb-b837-0640bc7822b2
    order: 1
slug: dashboard-with-filters-2
spaceSlug: jaffle-shop
version: 1
downloadedAt: "2025-03-10T10:19:06.515Z"
```
