### ISSUE TITLE
I would like to turn off grouping when there's only one time interval for my "date"/"timestamp" dimension

### ISSUE THREAD

**Issue by joaoviana** [lightdash/lightdash#14137]
### Description

Currently, when I define a "date"/"timestamp" dimension, and apply a time interval, it will appear grouped on the UI, even if there's only one time interval

There should be a way to **ungroup** this date dimension, and display it as a "single dimension"

example

```yml
dimension:
            label: "Timestamp (with timezone)"
            type: timestamp
            time_intervals:
              - DAY
```

<img width="334" alt="Image" src="https://github.com/user-attachments/assets/d6870523-8578-4266-ac3f-955379843af7" />

### What problem does this solve?

Removes one extra click

**Comment by jpetey75** [comment]
This can be accomplished by using the `sql` config in the dimension or by turning off intervals (if you only want to surface the date or timestamp field directly from the database).

Assuming your dbt column is `created_at` the dimension configs would look like this:


this surfaces the timestamp field and truncates to date
```
meta:
  dimension:
    label: "Day"
    type: date
    time_intervals: OFF
    sql: date(${TABLE}.created_at)
```

or this just surfaces the timestamp (no date or intervals)

```
meta:
  dimension:
    label: "Timestamp"
    type: timestamp
    time_intervals: OFF
```
