### ISSUE TITLE
I want to be able to hide fields from appearing in the Explore from my joined model, but still be usable in my .yml file

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#14180]
### Description

Right now, you can only use the fields from a joined model that are specified in the `fields` section of the join. 

But, sometimes, I don't want fields to appear in the sidebar in the Explorer, but I want them available to be used in the .yml file in defining metrics, etc. 

My suggestion is to add a `hidden` option in the `joins` --> `fields` configuration that allows users to hide fields from the joined model in the sidebar, like this:

```
meta:
  joins:
        - join: deals
          type: left
          sql_on: ${accounts.id} = ${deals.account_id}
          fields: [unique_deals, new_deals, won_deals, lost_deals, stage]
            hidden: [unique_deals, won_deals]
```
