### ISSUE TITLE
Lightdash crashes if you use the wrong dimension type `numeric`

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1420]
### Describe the bug

Set a dimension in your `schema.yml` file to `numeric` instead of `number` - it compiles but crashes in the Lightdash UI (completely blank screen).

Should get a more sensible error 

### To Reproduce

```
        - name: my_column
          meta:
            dimension:
              label: "some_label"
              type: numeric   # this should be "number" rather than "numeric"
```

### Expected behavior

A sensible error message
