### ISSUE TITLE
Metric filter only picking one value when having a value list for boolean dimension

### ISSUE THREAD

**Issue by almeidabbm** [lightdash/lightdash#14227]
### Description

When I filter a boolean dimension in my metric in the yaml file using a list of values, it is only picking one of the values to filter by.

### Steps to Reproduce the Bug or Issue

1. Add the following dimension and metric to the `events.yml`
```yaml
      - name: event_boolean
        description: ""
        meta:
          dimension:
            type: boolean
            groups: ["events"]
            sql: |
              case 
                when ${event} is null then ${event}
                when ${event} = 'song_played' then true
                else false end
          metrics:
            boolean_count:
              type: count
              filters:
                - event_boolean:
                    - false
                    - true
```

In this case, `event_boolean` can be `true, false` or `null`. On our filter for the count metric, we just want to count when `event_boolean` is either `false` or `true`
2. Results will look like:
![Image](https://github.com/user-attachments/assets/e275f166-2f4d-4790-865a-1649300066a9)

### Cloud or self-hosting

None
