### ISSUE TITLE
missing sql property in schema yaml (path: meta.metrics) doesn’t throw proper error

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#14408]
### Description

When a metric (in model's meta `meta.metrics`) is defined without a required sql field in YAML, CLI errors with javascript runtime error instead of helpful error message:

```
- ERROR> somemodel : Cannot read properties of undefined (reading 'replace')
```

CLI should surface a clear error during validation indicating that the metric is invalid due to a missing sql field.

### Steps to Reproduce the Bug or Issue

add meta metric in your yaml file and run lightdash validate

```
meta:
  metrics:
    testing:
      type: number
      label: testing something
      format: '€#,##0.00'
      groups:
        - testing
```

### Cloud or self-hosting

None
