### ISSUE TITLE
Error when using quoted column identifiers with snowflake

### ISSUE THREAD

**Issue by Vfisa** [lightdash/lightdash#1504]
### Describe the bug

`dbt run` and `dbt test` finishes successfully, i.e. correct table and column specification, though lightdash cannot parse column specification from schema.yml. Note: Lightdash correctly sees table name, as per screenshot.

`dbt_project.yml` :   
```
quoting:
  database: false
  schema: true
  identifier: true
```

### Expected behavior

Lightdash correctly respect quoting, especially when using snowflake as a backend

### Screenshots

<img width="745" alt="Screen Shot 2022-03-04 at 11 17 53 AM" src="https://user-images.githubusercontent.com/2714554/156830473-a3d431d8-e4e5-4289-8de0-d2dc66089c57.png">
<img width="473" alt="Screen Shot 2022-03-04 at 11 10 47 AM" src="https://user-images.githubusercontent.com/2714554/156830476-644d2c8a-214b-4440-a8fb-09006f1579a0.png">
<img width="635" alt="Screen Shot 2022-03-04 at 11 07 14 AM" src="https://user-images.githubusercontent.com/2714554/156830479-266db032-ea6b-4c13-9d70-9d4617cdbc07.png">

**Comment by TuringLovesDeathMetal** [comment]
Good find @Vfisa - we've been having some struggles with Snowflake column parsing, but we're getting there!

@owlas you ever run into this before?

**Comment by Vfisa** [comment]
Hi, any update on possible solution? I think lightdash just needs to respect the quoting from `dbt_project.yml`

**Comment by ZeRego** [comment]
Hi @Vfisa I agree that we should pick these settings from dbt_project.yml. I can't give an estimate on how simple/complicated a fix for this will be without looking better at the code but I don't think we will have bandwidth to pick this issue this week. I hope we can pick this in the following week :)

**Comment by owlas** [comment]
@all-contributors add @Vfisa for bugs

**Comment by owlas** [comment]
Hey @Vfisa thanks for opening the bug, just to keep you up to date. we're making some final adjustments to charts this week. We'll reprioritise again next Tuesday! In the mean time I'm going to take a look at the code to determine how complex this will be to support.

Quoting is such a headache 😰

**Comment by alex5995** [comment]
Hi, any update on this?

**Comment by dalebradman** [comment]
I believe this issue also exists for Redshift. For example:

```
models:
  - name: my_table
    columns:
      - name: '"event_source.event_source_stream.source_stream"'
```

Results in the generated SQL which fails:
```
SELECT
  "my_table"."event_source.event_source_stream.source_stream" AS "my_table_"event_source.event_source_stream.source_stream""
FROM "a_database"."events"."my_table" AS "my_table"


GROUP BY 1
ORDER BY "my_table_"event_source.event_source_stream.source_stream""
LIMIT 500
```

**Comment by ZeRego** [comment]
Hi @dalebradman 👋 

We documented a solution when the columns have special chars. Let us know if this works for you 😃 
https://docs.lightdash.com/references/dimensions#using-special-characters-or-capital-letters-in-your-column-names

**Comment by dalebradman** [comment]
Ah okay great, that does seem to have worked with a few adjustments:

```
models:
  - name: my_table
    columns:
      - name: "event_source.event_source_stream.source_stream"
        quoting: false
        meta:
          dimension:
            type: string
            sql: '${TABLE}."event_source.event_source_stream.source_stream"'
```
