### ISSUE TITLE
Browserless-chrome : Failed to send scheduled delivery Screenshot failed: locator.all: Execution context was destroyed, most likely because of a navigation

### ISSUE THREAD

**Issue by Geethika-sg** [lightdash/lightdash#15229]
Hi, 

trying to enable the Headless chrome feature that Lightdash suggests so as to send the screenshots of Chart details via scheduled delivery. The .csv Option works Fine but not the "image and pdf" one. 

The Errors I come accross are as below (Errors displayed on the dashboard)  :

1. Failed to send scheduled delivery Screenshot failed: locator.all: Execution context was destroyed, most likely because of a navigation. 

2. Failed to send scheduled delivery

Screenshot failed: browserType.connectOverCDP: WebSocket error: connect ECONNREFUSED IP_address:3000 Call log:

```
ws://lightdash-browserless-chrome:3000/
ws://lightdash-browserless-chrome:3000/ error connect ECONNREFUSED IP_address:3000
```
===========================

Further when I check the logs of the browserless-chrome Pod I get the errors as below :

=============================

```
Unhealthy
Readiness probe failed: Get "http://ip_address:3000/pressure": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

On checking the details of to which Port the service listens to internally - it is 3000 

I have also added readiness and Liveliness parameters as below  under browserless-chrome section in the File :

```
livenessProbe:
      httpGet:
        path: /pressure
        port: 3000
      initialDelaySeconds: 60
      timeoutSeconds: 20
      periodSeconds: 30
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /pressure
        port: 3000
      initialDelaySeconds: 90
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 3
```

The service details in the cluster is as below :

```
Name:                     lightdash-blue-browserless-chrome
Namespace:                namew
Labels: 
                          helm.sh/chart=browserless-chrome-0.0.4
Annotations:              <none>
Selector:                 app.kubernetes.io/instance=lightdash-blue,app.kubernetes.io/name=browserless-chrome
Type:                     ClusterIP
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       IP_address_1
IPs:                      IP_address_1
Port:                     http  3000/TCP
TargetPort:               3000/TCP
Endpoints:                IP_address_2:3000,IP_address_3:3000,IP_address_4:3000 + 0 more...
Session Affinity:         None
Internal Traffic Policy:  Cluster
Events:                   <none>
```

![Image](https://github.com/user-attachments/assets/da1848da-f9ce-49b8-b8b1-e2b777032b73)

Further  I get : 

```
curl: (6) Could not resolve host: lightdash-browserless-chrome
on executing below command : 
curl http://service-name:3000/pressure.
But still I land to the
Readiness Probe Failure errors.
```

Lightdash Documentation : https://docs.lightdash.com/self-host/customize-deployment/enable-headless-browser-for-lightdash

As per the above Document I have also enabled the Parametrs as :

```
   - name: HEADLESS_BROWSER_HOST
      value: "lightdash-browserless-chrome"
    - name: HEADLESS_BROWSER_PORT
      value: "3000"  
    - name: SITE_URL
      value: "https://lightdash.test.com"
```

The screenshots Option doesn't work .
