### ISSUE TITLE
`!null` filter on timestamp fields causes SQL error in Databricks

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#15382]
When using the `!null` filter condition on a timestamp field in Lightdash YAML, users encounter a SQL error in Databricks. The error message indicates that the value 'Invalid date' of type STRING cannot be cast to TIMESTAMP. This issue does not occur with non-timestamp fields, and the filter works as expected in other warehouses (e.g., BigQuery).

**Example YAML:**
```
count_of_completed_reminders:
  label: Count of completed reminders
  type: number
  description: The count of reminders that have been completed.
  filters:
    - is_open_reminder: true
    - completed_at: "!null"
```
Where `completed_at` is a timestamp field.

**Error message:**
```
[CAST_INVALID_INPUT] The value 'Invalid date' of the type "STRING" cannot be cast to "TIMESTAMP" because it is malformed. Correct the value as per the syntax, or change its target type. Use try_cast to tolerate malformed input and return NULL instead. SQLSTATE: 22018
```

**Notes:**
- The issue appears specific to timestamp fields on Databricks.
- The filter works for non-timestamp fields and in other warehouses.
- Both `null` and `NULL` (case) variants were tested.
