### ISSUE TITLE
Health check hangs when no internet access

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1553]
### Describe the bug

If there is no internet access available, the health check endpoint hangs

I suspect it comes from docker hub polling for latest app version

### Expected behavior

Should pass health check skipping any features that need internet access

**Comment by owlas** [comment]
I'm still trying to reproduce this error, it was reported by a user. If I kill internet access completely I can't reproduce. I think I need to try using a firewall wall on external traffic.

**Comment by owlas** [comment]
Update: example k8s network policy causing this error

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testpolicy
  namespace: lightdash
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # allow traffic from the ingress
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: ingress-nginx
    # allow traffic from any pod in namespace
    - from:
        - podSelector: {}
  egress:
    # allow dns traffic
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    # allow traffic out to the ingress
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: ingress-nginx
    # allow traffic to any pod in namespace
    - to:
        - podSelector: {}
```
