### ISSUE TITLE
Wrong syntax for dbt metrics, should use `ref`s

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#1655]
### Describe the bug

The lightdash approach to writing metrics expects:

```yaml
metrics:
  - name: new_customer
    label: New Customers
    model: customers
    description: The number of paid customers
```

But the model name should be a `ref` or `dbt_metrics` queries fail to compile:

```yaml
metrics:
  - name: new_customer
    label: New Customers
    model: ref('customers')
    description: The number of paid customers
```

```
Runtime Error
  Compilation Error in model ... (models/...sql)
    list object has no element 0
```
