### ISSUE TITLE
Cannot read properties of undefined (reading 'toUpperCase') 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1724]
### Describe the bug

I was writing my metrics like this:
```
  - name: queries_executed_num
    description: 'Total number of queries executed on the given date'
    meta:
      metrics:
        total_queries_executed:
          - type: sum
          - description: The total number of queries executed over the given range of dates.
```

instead of writing them like this:
```
  - name: queries_executed_num
    description: 'Total number of queries executed on the given date'
    meta:
      metrics:
        total_queries_executed:
          type: sum
          description: The total number of queries executed over the given range of dates.
```

And this was the error message I got:

`cannot read property 'toUpperCase'`

^It took me sooooooo long to figure out what I'd done wrong because I couldn't understand the error message. 

### Expected behavior

There should be a more helpful error message when there's a problem with teh metric syntax. Specifically:
1. It should tell me what metric is the problem (ideally)
2. It should tell me that the metric syntax is the problem
