### ISSUE TITLE
I want to be able to create default filters in my Explores

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1735]
### Description: What is it?

I want to add default filters to my Explores so that when people use them, they automatically have filters applied to them. 

These filters are either:
- empty, but the field is filtered to an empty value so users are pushed to filter on that field
- filled with one or many values 

### Problem: What problem does this solve?

Some datasets are really large or require specific filters to "make sense". For example, for 99% of queries I run using my `accounts` table, I want `account_closed = FALSE`. But, I still want to be able to query _**all**_ accounts (open or closed) for some queries. By default, I want to filter for `account_closed = FALSE` so other folks don't have to remember to add this filter each time, but I want the option to be able to remove it.

Another example from a user:
we are dealing with a massive amount of data partioned by date. We would like to force a filter on the date in order to force the user to apply a date. It will first avoid to have an error because you can not query a partioned table without a where condition on the date

### What: Roughly, what does this look like in the product?

- [ ] users can apply filters to Explores in their dbt projects. 
- [ ] The filters are applied on a model level (i.e. under `model` -->`meta` --> `filters`)
- [ ] the filter syntax is the same as what's used here: https://github.com/lightdash/lightdash/issues/3126
- [ ] there are three types of filters: 
    - `default` filters are applied to the table, but can be overridden in the UI (the same way as dashboard saved filters can be overriden, for example). 
    - `required` filters can have their values changed, but cannot be removed from the filters list in the UI
    - `sql_where` these are fixed filters cannot be changed and cannot be removed - these are actually hidden from the user in the UI. They'd only be visible in the compiled SQL. (this is the type we have already using `sql_where`)

```yaml
models:
  name: users
  meta:
      default_filters: 
          - created_date:
               field: ${created_at_date}
               value: >= '2022-05-21'
       required_filters:
         - created_date_required:
               field: ${created_at_date}
               value: >= '2022-05-21'
      sql_where: ${created_at_date} >= '2022-05-21' # we could change the name of `fixed filter` to `sql filter`
```

OR something like: 

```yaml
models:
  name: users
  meta:
    default_filters:
      - filter: ${created_at_date}
         value: >= '2022-05-21'
         required: no
     sql_filters: ${created_at_date} >= '2022-05-21' # This is a fixed filter - how can we fit this into the other format??
```

### Needs spec:

- what do `required` and `default` filters look like in the UI? 
- The current format in the .yml doesn't work - we need to be able to split out the filters into fields + values in the UI. But how does this work with existing `sql_filter`? 
- add docs
- add analytics events

**Comment by owlas** [comment]
If we want this to be fully compatible with the UI we have for filtering and interact well with dashboard filters + explore filters, the structure of the filters will need to be the same.

So instead of:

```
    filters:
      - filter: ${created_at_date} # this should match the field. You can also filter on joined fields.
          sql: >= '2022-05-21' # required
          type: default # the default value for type is 'default'
```

It would be more like:

```
target:
  fieldId: created_at_date  # not sure if this should be referenced with ${}
operator: "inThePast"
values: [5]
settings:
  unitOfTime: "years"
  completed: false
```

^ this is obviously pretty annoying to write and we could figure out a simplified structure. But we need the filters to be compatible with this layout.


---

`type: default|required`

Instead of `type` could we have a field `isEditable: true|false` or `isRequired: true|false` seems more intentional
