### ISSUE TITLE
I want to group together common metrics/dimensions in my Explores.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#1851]
### Description: What is it?

I want to be able to add `dimension_groups` or `metric_groups` to my Explores. 

These groups would appear in Lightdash in my Explore and override the default flat-list of dimensions and metrics in the sidebar.

e.g. user_name, user_country, user_age, user_gender are all grouped together in a drop down group called  user demographics

### Problem: What problem does this solve?

It's hard to navigate through all of the metrics + dimensions in an Explore and know which are related to each other (or even relevant!)

### What: Roughly, what does this look like in the product?

In your YAML, you'd write:

```yaml
columns:
  - name: user_id
    meta:
      dimension:
        group_label: "User attributes"
      metrics:
        count_distinct_user_ids:
          type: count_distinct
          group_label: "User attributes"
```

- [ ] You would define dimension/metric groups in your YAML file, then these would appear in the sidebar as a toggle-list.
- [ ] You can search for these groups 
- [ ] If I have a date/timestamp toggled dimension, it is still a toggle inside of the group toggle (basically, toggles can be nested - but _**only**_ for dates)
- [ ] a column can only be included in a _**single**_ group (not many groups)

Wireframe here:
https://www.figma.com/proto/Mhuwki1Bj1akQIwPyr1gWw/Lightdash-product?node-id=5533%3A89295&scaling=min-zoom&page-id=5438%3A86217&starting-point-node-id=5533%3A89295&show-proto-sidebar=1
Hi-fidelity designs coming soon, **but first step is to add the groups in, similar to how we deal with date and time groups.**
