### ISSUE TITLE
Be able to hide certain dimensions and metrics from Lightdash. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#194]
Right now, if your dimension exists in your .yml file, it will appear in Lightdash. 

There should be a way to hide a dimension. 

E.g. in the `meta` tag, you could have a parameter: `hidden`: `true`

By default, hidden would = `false`

You should be able to hide the dimension but still have metrics. E.g. if I had a dimension `sales`, I might never want `sales`, but I would want to be able to calculate `total_sales`. 

So, something like this:
```
columns:
  name: sales
    meta: 
      dimension: 
        hidden: true
      metrics:
        total_sales:
          type: sum 
```
