### ISSUE TITLE
I want to specify which fields to include in my joined table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2009]
### Description: What is it?

When I join an explore, I want to be able to specify which fields are available in the joined table in my explore. 

E.g. if I join `organizations` to `users`, I only want `organization_id` and `organization_name` to appear in the joined `organizations` table in my `users` explore.

### Problem: What problem does this solve?

only some of the columns from my joined table may be relevant to join to my other table.

### What: Roughly, what does this look like in the product?

- in the YAML file, there's a way to `include-fields` or something in the `join`. 

e.g. 
```
models:
- name: my_model
  description: 
  meta:
    joins:
    - join: other_model
      sql_on: ${my_model.id} = ${other_model.id}
      include_fields: ['users', 'user_id', 'test']
```

By default, `include_fields` is set to `all`
