### ISSUE TITLE
Reference metrics/dimensions from all joined models

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2049]
### Description: What is it?

Imagine a scenario where I have three models: `organizations`, `users`, and `user_details_pii`. 

`users` is joined to `organizations`
`user_details_pii` is joined to `users`

I have a metric in `users` that requires a field from `organizations`. 

you should be able to click on that metric in `user_details_pii` and just see the results. 

(here's the example YAML file for these three models)

```yaml
version: 2
models:
- name: organizations
  columns:
  - name: organization_id
  - name: organization_type
```

```yaml
version: 2
models:
- name: users
  meta:
    joins:
    - join: organizations
      sql_on: ${users.organization_id} = ${organizations.organization_id}
  columns:
  - name: user_id
    meta:
      metrics:
        count_cloud_users:
          type: count_distinct
          sql: IF(${organizations.organization_type} = 'cloud', ${users.user_id}, NULL)
```

```yaml
version: 2
models:
- name: user_details_pii
  meta:
    joins:
    - join: users
      sql_on: ${users.user_id} = ${user_details_pii.user_id}
  columns:
  - name: user_id
```

### Problem: What problem does this solve?

Right now, if I have the setup described above, then `user_details_pii` just throws an error and doesn't appear in my models. 

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/31848148/167634591-064e5968-fecd-4c8c-9743-4a378e8a66cf.png">

Sometimes, there are metrics that I want to use which require me to reference another data model. These should "just work" when I pull them across to other models via joins

### What: Roughly, what does this look like in the product?

- [ ] In the example above, if I went to `user_details_pii` and clicked on `count_cloud_users` from the joined `users` table, it would work. 
- [ ] I wouldn't have to join `organizations` to `user_details_pii`.
