### ISSUE TITLE
With a custom SQL field, if you reference fields from joined tables, it breaks

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2071]
### Describe the bug

If I have a field in `orders` like this: 

```yaml
columns: 
  - name: order_name
     meta:
       dimension:
         sql: ${TABLE}.order_id
         type: string
```

Then I reference this field in `deliveries` which is joined to `orders`:

```
models:
- name: deliveries
  meta:
    joins:
      - join: orders
        sql_on: ${orders.order_id} = ${deliveries.delivery_id}
  columns:
    - name: order_status
       meta:
         dimension:
           sql: IF(${orders.order_name} IS NULL, 'undelivered', 'delivered') 
```

^This will break. 

I tried to change `${orders.order_name}` to `${orders.order_id}`, but it still doesn't work. 

I don't know how to fix this 🤔 

### Expected behavior

I should be able to use `${orders.order_name}` in the joined table reference in `deliveries`
