### ISSUE TITLE
Lightdash isn't actually using the schema I've defined in my project settings

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2084]
### Describe the bug

I've defined `dbt_khindson` as my schema in my project settings (i.e. my dev schema). But, if I try to run any queries, it points to `lightdash-analytics.prod` (not my `dbt_khindson` schema). 

### To Reproduce

1. Change your schema to anything that isn't `prod`. 
2. Try running a query. 
3. See which schema it's referencing in the query

### Expected behavior

Lightdash should be querying from my `dbt_khindson` schema. 

### Screenshots or Loom video

<img width="780" alt="image" src="https://user-images.githubusercontent.com/31848148/168014501-83bfbc56-914b-491e-bfbb-66b4ed9f1db1.png">
<img width="698" alt="image" src="https://user-images.githubusercontent.com/31848148/168014457-6d850a14-a518-4f95-87a0-d1ec6655f23e.png">

**Comment by TuringLovesDeathMetal** [comment]
**Note:** This is something we sort of noticed from the start. 

E.g. our `pii` tables are in a completely different dataset (`lightdash-analytics-pii`) and yet, they're somehow available in Lightdash...

**Comment by rephus** [comment]
@TuringLovesDeathMetal any idea if this is just affecting BigQuery/Snowflake ? I think I've done this on postgres and it was working ok (I'll test it again now anyway)

**Comment by TuringLovesDeathMetal** [comment]
No, sorry! I've only checked on BigQuery and Will was having this error in Snowflake

**Comment by rephus** [comment]
I can replicate this on postgres. The schema change is not applied until we run `Refresh dbt` . @TuringLovesDeathMetal could you confirm this is fixing the issue ? If so, I can just ensure we trigger refresh-dbt on project schema update

**Comment by TuringLovesDeathMetal** [comment]
ya, still not working for me after `refresh dbt` :/

<img width="919" alt="image" src="https://user-images.githubusercontent.com/31848148/168024196-6e99651e-6a7a-4bf7-bd96-5504b4a1f879.png">

**Comment by rephus** [comment]
After adding `compileAllExplores` to `update` ![Peek 2022-05-12 10-13](https://user-images.githubusercontent.com/1983672/168024167-51b78f7e-a913-4b33-95d5-8ae1f9a73531.gif)

**Comment by TuringLovesDeathMetal** [comment]
Jose said something in Slack which might be relevant:

> isn’t this the case were their dbt project relies on a env var to point to dev ? or it depends on the profile name ? which we use prod

This is what my profiles.yml file looks like:

```yaml
lightdash_analytics:
  outputs:
    dev:
      dataset: dbt_khindson
      location: us
      method: oauth
      priority: interactive
      project: lightdash-analytics
      retries: 1
      threads: 1
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: prod
      location: us
      method: oauth
      priority: interactive
      project: lightdash-analytics
      retries: 1
      threads: 1
      timeout_seconds: 300
      type: bigquery
```
