### ISSUE TITLE
Support dbt metric filters

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2203]
### Description: What is it?

Some users would like to use dbt's metric filter syntax rather than baking filters into the sql:

```yaml
  - name: dbt_model_runtimes
    label: DBT model runtimes
    model: fct_dbt_model_runtimes
    description: "Runtimes of DBT models in prod runs"

    type: sum
    sql: TOTAL_NODE_RUNTIME

    timestamp: QUERY_COMPLETED_DATE
    time_grains: [day, week, month, year]

    filters:
      - field: ENV_DBT_CLOUD_JOB_NAME
        operator: '='
        value: 'Production Run'
```
