### ISSUE TITLE
I want to be able to set the separator style for my field

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#2216]
### Description: What is it?

I want to be able to remove the default commas for a numeric column.

### Problem: What problem does this solve?

Some numeric values are actually IDs that we don't want commas to appear in (e.g. Fivetran and Rudderstack make IDs numeric)

### What: Roughly, what does this look like in the product?

- Same separator style options as in the big number chart, except this exists in YAML and has the option for `None` (i.e. no default separator formatting - just show me how it is in my database)

- This is only available for numeric type columns

```yaml
name: user_id
  meta:
    dimension: 
      separator: 100,000.00 # or 100.000.00 or 100000.00 or 100 000.00 or None
```

![image](https://user-images.githubusercontent.com/31848148/169980943-47388ba4-096b-4c58-9cc8-5099eaf1d659.png)
