### ISSUE TITLE
Table viz doesn't show custom field labels

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2231]
### Describe the bug

If I set my dimension with a custom field name, it doesn't show in the table viz. It does show in the explore view and charts etc.:

```
columns:
  - name: column_name
    meta:
      dimension:
        label: much better name
```
