### ISSUE TITLE
The app crashes when there are dimensions and metrics in the same model. 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2349]
### Description

The app crashes when there are dimensions and metrics in the same model. 
The field id is a combination of the model name and the field name and it can be the same for a dimension and a metric.

I think we should throw an error when connecting/refreshing the dbt project to indicate there are duplicate references in the dbt project. 

If metric name === dimension name -> "Metric X can't have the same name as existing dimensions"
If metric name === metric name -> "Found multiple metrics with the name X"

### To Reproduce

Example of a column in the `schema.yml` which has a metric with the same name:

```
      - name: amount
        meta:
          metrics:
            amount:
              type: sum
          dimension:
            hidden: true
```

In development mode we get this error when selecting the metric from the sidebar:
<img width="544" alt="Screenshot 2022-06-07 at 16 37 45" src="https://user-images.githubusercontent.com/9117144/172422567-87c86e51-4500-4bdf-87bd-838eac75dd8f.png">

### App Version
 0.132.4
