### ISSUE TITLE
Don't overwrite dimension types in `lightdash generate`

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#2371]
### Description

If I update the dimension type for a column in my `schema.yml`, `lightdash generate` will overwrite it: 

```
columns:
  - name: user_id
    meta:
      dimension:
        type: number
```
