### ISSUE TITLE
Search function for metrics/dimensions in sidebar only uses the dimension name and not the label

### ISSUE THREAD

**Issue by hamzahc1** [lightdash/lightdash#2559]
### To Reproduce
In this example, the yml file for the dimension is: 
```
- name: country
  description:  Market
  meta:
    dimension:
      label: 'Market'
```
When searching for market, nothing shows up. You have to search for country. 

![image](https://user-images.githubusercontent.com/14341285/175613451-d5713ce8-9597-4c19-aa54-e67cb3ec8113.png)

![image](https://user-images.githubusercontent.com/14341285/175613424-84d7f128-dd51-4236-bb95-004a5e1a5831.png)

### App Version

0.162.0
