### ISSUE TITLE
custom dimensions and measures, table calculations ala Looker

### ISSUE THREAD

**Issue by djayatillake** [lightdash/lightdash#266]
https://docs.looker.com/exploring-data/using-table-calculations
https://docs.looker.com/exploring-data/adding-fields/custom-measure

I think a way this could be better done is for them to be defined in sql or some kind of natural language/GUI... Looker has opted for some horrible medium which is something like an excel function

**Comment by owlas** [comment]
Hey @djayatillake, glad you opened this one! We've been experimenting a little behind the scenes.

I think you're right that there's two workflows here: 

1. (**supported**) Ability to define custom metrics with raw sql (ultimate flexibility) inside dbt models
2. (**not supported**) Ability to perform custom table calculations in the UI


## Custom metrics with raw SQL (supported)

This is actually possible today and quite similar to looker: 

* **Aggregate metrics** accept a raw sql string and lightdash will then aggregate the result. e.g. `rawSql: col1 + col2` in a `sum` metric gives: `SUM(col1 + col2)`
* **Non-aggregate metrics** accept a raw sql string that lightdash expects to already be aggregated e.g. `rawSql: SUM(col1 + col2)` for a `number` metric.

There are even some calculations that typically get pushed to the UI (Looker would call them post-sql measures) but could actually done using analytic functions in sql.

A personal favourite is a lightdash metric for a cumulative sum:

```
columns:
  - name: sale_atm
    description: Total amount spent at checkout
    meta:
      metrics:

        # this metric will just be the sum of revenue
        total_revenue:
          type: sum

        # this metric will be a rolling sum of revenue
        cumulative_revenue:
          type: number
          rawSql: SUM(${total_revenue}) OVER(ROWS UNBOUNDED PRECEDING)
```

Pros: written as code, version controlled, etc.
Cons: hard to understand, still not accessible to non-technical users 


## Table calculations defined through the UI (not-supported)

So we still have the dilemma of how people that don't use SQL do calculations in the UI. I'm quite skeptical of many low-code sql builders. Looker's excel-style formulas is pretty common across tools.

We're still deciding what the right level of config should be in the UI. Today you can only create calculations as code in your dbt models. That may change in future

What are you thoughts? Should analysts be able to run calculations in the UI? Are there better alternatives to exposing excel-like or pseudo-sql calculations to non-technical users in the UI?
