### ISSUE TITLE
Where do metrics defined using dimensions from joined tables exist?

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#276]
Right now, all metrics exist in a model's columns' meta tag. E.g. 
```
models:
  - name: pages
    columns:
      - name: test_col
        meta:
          metrics:
            test_col_count_if_true:
              type: count_distinct
              sql: 'IF(${joined_table.other_col}, ${test_col}, NULL)'
```

We'll need to decide where metrics/dimensions defined using joined models exist in the models part of the schema file, or if they exist in the exposures bit of the schema file and how this will be presented in the UI as well...(e.g. if they get defined in the models bit, then are any metrics with joined dimensions included in the `tables` in the Lightdash UI?)

**Comment by TuringLovesDeathMetal** [comment]
There are two possibilities for this:

## Option 1: metrics/dimensions built from joined tables are included under the Exposures meta tag

In this case, you'd have model-specific metrics in the model's meta. But, for metrics that reference joined models, you'd have to define these in the meta tag in the Exposures.

In the list of metrics/dimensions in Lightdash, these joined metrics would sit _**outisde**_ of the model toggle-lists (maybe be in their own toggle list? Something like `joined metrics`?)

**Pros:**
- Keeps joined "stuff" completely separate from solo model stuff. 

**Cons:**
- if you have loads of exposures, you might want a joined metric to be easily added to all of them (you could get this by having them defined in the model's meta tag, instead of the exposures meta tag)
- metrics are now being defined in multiple places. 

```yaml
exposures:

  - name: users 
    type: dashboard  # dbt specific - dashboard|notebook|analysis|ml|application
    description: "Use this exposure for analyses about users (NOT over time - if you want users over time, check out user_stats)"  
    owner: katie@lightdash.com

    depends_on:                  # These tables are available as joins
      - ref('transactions')
      - ref('projects')

    meta:
      base: ref('users')
      joins:
        - model: ref('transactions')
          sql_on: ${users}.user_id = ${transactions}.user_id
				- model: ref('projects')
          sql_on: ${users}.user_id = ${projects}.user_id
			metrics:
				count_unique_admin_users:
					type: count_distinct
					sql: "IF(${projects}.is_admin, ${users}.user_id, NULL)"
	
```

## Option 2: All metrics are defined in a model's meta (even metrics from joined models)
[This is what Looker does](https://docs.looker.com/data-modeling/learning-lookml/sql-and-referring-to-lookml#:~:text=%24%7Bview_name.field_name%7D%20references%20a%20dimension%20or%20measure%20from%20another%20view.%20For%20example%3A). In this scenario, you'd define _**all**_ of your metrics under the model's meta. 

The metrics would **only appear in your Exposures in Lightdash if they contained all of the joined tables it needs.**

For example, if you had a .yml that looked something like this:
```yaml
version: 2

models:
  - name: users
    description: "One row per user per day"

    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
        meta:
          metrics:
            count_unique_users:
              type: count_distinct
						count_unique_admin_users:
							type: count_distinct
							sql: "IF(${projects}.is_admin, ${users}.user_id, NULL)"
```

`count_unique_admin_users` would only appear in your Exposure if the Exposure contained `projects` + `users`. Otherwise, it wouldn't appear in your exposure. 

**Pros:**
- all of your metrics are in one place
- it's similar to Looker, so folks might be expecting this
- you can define a metric once and use it in multiple places.

**Cons:**
- it could break if you remove joins/a join doesn't exist in the first place. 
- stuff that depends on join logic doesn't "live" beside the join logic
- it's complicated to add either error handling (if you don't have a join that exists) or to program this to make it so that metrics only appear in some explores, and not in others. [Here's how Looker shows these errors](https://community.looker.com/lookml-5/dimension-referencing-other-view-won-t-work-11919#:~:text=I%20must%20be%20doing%20something%20incorrect%2C%20but%20the%20CASE%20in%20the%20Arrangements%20view%20won%E2%80%99t%20let%20me%20use%20anything%20other%20than%20%E2%80%9Caccount%20list%E2%80%9D%20or%20gives%20me%20an%20error%3A) (e.g. if I  selected `count_unique_admin_users`, but I haven't joined `projects` to `users` in the Exposure I'm using)
