### ISSUE TITLE
Better YAML error parsing on CLI 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#2783]
### Description

If there is an error when parsing  the dbt_proyect.yml file (eg: duplicated key) it will return instead a "file not found" error .

We need to fix this recursive catch https://github.com/lightdash/lightdash/blob/main/packages/cli/src/dbt/context.ts#L28

### To Reproduce

add a duplicated key to any element inside dbt_project.yml

eg: 

```
models:
  jaffle_shop:
      materialized: table
      materialized: table
```

run `lightdash generate`

You will see an `ENOENT: no such file or directory, open '/dbt_project.yml` error, but instead you should see something like

![image](https://user-images.githubusercontent.com/1983672/180976266-329aef26-cd3a-4ae9-9843-7bfa7adf91cf.png)
