### ISSUE TITLE
Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2789]
### Description

Error when refreshing dbt using custom sql and percent formatting

### To Reproduce

Dimension yml
```
      - name: days_since_last_order
        description: Number of days since the customers last order
        meta:
          dimension:
            hidden: false
            sql: "${days_since_last_order} * 100"
            format: "percent"
```

<img width="699" alt="Screenshot 2022-07-26 at 15 45 48" src="https://user-images.githubusercontent.com/9117144/181037435-4183c043-f725-461d-b006-cd126066d9aa.png">
