### ISSUE TITLE
Getting ECONNREFUSED ::1:888 on CLI error

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#2862]
### Description

When connecting to `redshift` via tunnel, we get an error on CLI 

when trying `lightdash generate` or even `lightdash preview`

`dbt run` works though 

![image](https://user-images.githubusercontent.com/1983672/182895482-bfb46e6e-3a18-471b-a2d5-2b4815047756.png)

 
### To Reproduce

Profile

```
jaffle_shop:
  target: jaffle
  outputs:
    dev:
      type: redshift
      host: localhost
      port: 8888
      user: redshift
      pass: password
      dbname: prod
      schema: jaffle
```

Connect via tunnel

`aws ssm start-session --target`
