### ISSUE TITLE
Metric doesn't use dimension custom sql

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2884]
### To Reproduce
```
      - name: num_participating_athletes
        meta:
          dimension:
            hidden: true
            sql: "num_participating_men + num_participating_women"
            type: number
          metrics:
            total_num_participating_athletes:
              type: sum
```
The dimension works, but the metric is saying "column eada.num_participating_athletes does not exist" (eada is the name of my table)

#### Possible solution:

In packages/common/src/types/dbt.ts convertMetric() we have:
`sql: metric.sql || defaultSql(columnName),`
In this case the sql is the result of defaultSql()
`\$\{TABLE\}.${columnName}`
We should be defaulting to the dimension sql instead.

### App Version

0.203.0
