### ISSUE TITLE
Error when using metrics type: string, date, boolean

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#2903]
### To Reproduce

I just tried adding this to my .yaml f[ollowing our docs](https://docs.lightdash.com/references/metrics#date):
```
    columns:
      - name: date
        meta:
          dimension:
            type: date
          metrics:
            max_date:
              type: date
              sql: 'MAX(${date})'
```
But then I get this error

**No SQL render function implemented for metric with type "date"**

Tech problem: 
We have typos in the metric types.
<img width="473" alt="Screenshot 2022-08-09 at 12 22 52" src="https://user-images.githubusercontent.com/9117144/183636058-d4de66d4-9929-4c11-841c-19b4ec79b49d.png">

### App Version

0.203.0
