### ISSUE TITLE
Add filters to metrics

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3126]
### Description

Metrics should be aware of filters on metrics. Today we solve this using `CASE` statements in the metric definition. But the downside is that these filters can't be re-purposed during "show underlying values"

For example, if I drill into "count active users" metric I should see all records for active users, today you'd just see all users (i.e. the explore view not filtered by active users).

we should introduce a new yaml syntax:

```yaml
metrics:
  count_active_users:
    type: count_distinct
    sql: ${TABLE}.user_id
    filters:
      - is_active: true
```

More details in thread: https://lightdash.slack.com/archives/C02NPFHF4F6/p1663237118300009
