### ISSUE TITLE
Specify fields for "show underlying values"

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3127]
In the definition for a metric I'd like to restrict the fields I see. this would make the "show underlying values" more focussed by only showing columns that are interesting for that drill down.

For example:

```yaml
metrics:
  count_active_users:
    type: count_distinct
    show_underlying_values:
      - user_id
      - name
      - email
      - source
```

Without this we default to showing all columns, which often shows a lot of irrelevant data
