### ISSUE TITLE
Support ssh key auth for snowflake

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3132]
### Description

My `profiles.yml` looks like this and isn't compatible with the lightdash cli

```yaml
my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: [account id]
      user: [username]
      role: [user role]

      # Keypair config
      private_key_path: [path/to/private.key]
      private_key_passphrase: [passphrase for the private key, if key is encrypted]
```
