### ISSUE TITLE
You should be able to create multiple dimensions based on a single column in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3232]
### Description

I want to group my ages, or revenue, or some other field into buckets. But, to do that, I need to actually add a dimension to my underlying data model 🤮 this is just a "version" or "grouping" of the underlying data, so it's a bit weird to add it to the underlying data model.

Instead, you should be able to have multiple dimensions defined for a single field in your dbt model. 

This is what it should look like: 

```yaml
- name: date
  meta:
    dimension:
      type: date
    additional_dimensions: 
      dimension_name_one:
        type: number
        label: "Day of Week"
        sql: "day_of_week(${date})" # optional - defaults to `
      dimension_name_two:
        type: boolean
        label: "Weekday or Weekend"
        sql: "case when day_of_week(${date}) < 5 then 'weekday' else 'weekend' end"
```

### Acceptance criteria

- [ ] I'm able to define multiple dimensions based on a single field in my dbt model. 
- [ ] These sub-dimensions can be used in other parts of the model YAML (e.g. referenced to create metrics, in the custom SQL of dimension definitions, etc.)
- [ ] These dimensions are defined in the column's `meta` tag under the parameter `additional_dimensions`
- [ ] You can define as many of these dimensions as you'd like. 
- [ ] When you use these in Lightdash, they appear as dimensions (and are treated as dimensions). 
- [ ] The same configuration applies as the `dimension` parameter
- [ ] If you don't define any `sql`, it just defaults to using `sql: ${column_name}` (this is so people can create the same dimension multiple times, but just have different formatting - e.g. `revenue`, `revenue in millions`, `revenue in thousands`, etc.)
- [ ] to define metrics based on a sub-dimension, you need to add them to the model's `meta` metrics, or use custom SQL in defining them under the column's meta. <-- add this to the docs!

### Analytics events

- [ ] add `additional_dimensions_num` to `project_compiled` event (maybe it's `count`? I forget the exact syntax, but copy whatever wording we use for the analytics event for metrics and dimensions counts in pojrect_compiled!)

### Docs

- update the `dimensions` reference doc. 
- [ ] add an example to the YAML blob: https://docs.lightdash.com/references/dimensions#dimension-configuration
- [ ] Add a row to the table of dimension configurations
- [ ] link the row to a new subsection called `Sub dimensions`
- [ ] Explain what sub dimensions are (You can define many dimensions based off of a single column in your dbt model using the `sub dimensions` parameter). 
- [ ] Give an example (you can use the example in the ticket that I've written out above! Where I want the same date field, but in many formats for my end users). 
- [ ] Explain that all of the parameters you can use in dimensions are also available to `sub dimensions`
- [ ] Explain how you can create metrics using sub dimensions (to define metrics based on a sub-dimension, you need to add them to the model's `meta` metrics, or use custom SQL in defining them under the column's meta.) - **Give examples of these!**

### Headway update!
write a headway update for this.
