### ISSUE TITLE
Drill down into calculated metrics 

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#330]
If I have a calculated metric e.g.:

```yaml
metrics:
  total_order_value:
    type: number
    sql: ${avg_order_value} * ${orders_count}
```

And I have a chart of the calculated metric, it would be great to have context of the sub metrics that are used to calculate it.

This means we would keep references to sub metrics (just like a DAG).

Then I'd want to be able to "drill" into a chart showing "Total order value" and quickly chart "avg order value" or "orders count" to get more context on the metric.
