### ISSUE TITLE
Feature request - Specify join relationship such as many to one, one to many, one to one, and many to many joins

### ISSUE THREAD

**Issue by olly-writes-code** [lightdash/lightdash#3393]
### Description

Specify join relationship such as many to one, one to many, one to one, and many to many joins. 

### What problem does this solve?

This lets the "_explore_" house lots of information. Empowering users to do aggregations but also dig into specific rows. With looker the relationship description ensures that upon aggregations the measure are summed, counted, etc correctly. Otherwise with we will have incorrect counting due to multiple one to many joins.

### Example (using redshift)
generate example tables
```
CREATE TABLE sale AS
(select 1 as sale_id);

CREATE TABLE gift_card AS
(SELECT 1 AS gift_card_id, 1 as sale_id, 20 as cash_value
UNION ALL SELECT 2 AS gift_card_id, 1 as sale_id, 20 as cash_value);

CREATE TABLE cash AS
(SELECT 1 AS TRANSACTION_id, 1 as sale_id, 10 as cash_value
UNION ALL SELECT 2 AS TRANSACTION_id, 1 as sale_id, 10 as cash_value);
```

#### Files

v_cash.sql
```
select * from cash
```
v_gift_card.sql
```
select * from gift_card
```
v_sale.sql
```
select * from sale
```
v_sale.yml
```
version: 2
models:
  - name: v_sale
    meta:
      joins:
        - join: v_cash
          sql_on: ${v_sale.sale_id} = ${v_cash.sale_id}
        - join: v_gift_card
          sql_on: ${v_sale.sale_id} = ${v_gift_card.sale_id}
    columns:
      - name: sale_id
        meta:
          dimension:
            number
  - name: v_cash
    columns:
      - name: transaction_id
        meta:
          dimension:
            number
      - name: sale_id
        meta:
          dimension:
            number
      - name: cash_value
        meta:
          metrics:
            total_cash_value:
              type: sum
  - name: v_gift_card
    columns:
      - name: gift_card_id
        meta:
          dimension:
            number
      - name: sale_id
        meta:
          dimension:
            number
      - name: cash_value
        meta:
          metrics:
            total_gift_cash_value:
              type: sum

```

Here's what the output looks like in lightdash
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/7778402/193979091-76aa6a0a-1040-4297-9d60-002700cacae8.png">
The answer should be 20 and 40 not 40 and 80 (double counts due to join mechanism)
