### ISSUE TITLE
add `suffix` formatting option to yaml

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3455]
### Description: What is it?

I want to be able to add a constant to the end of each value for a field

### What: Roughly, what does this look like in the product?

```yaml
name: distance
  meta:
    dimension: 
      suffix: 'km' # output would be '100 km' in Ligthdash
```

- these values are still treated as their original type when using them/manipulating them in a results table (e.g. treated as a number)
- if these values are used in table calculations, then their suffix is dropped. (e.g. table calculation = 'distance * 100' --> this would have no formatting applied to it)
