### ISSUE TITLE
I want to add a prefix

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3456]
### Description: What is it?
I want to be able to add a constant to the beginning of each value for a field

### What: Roughly, what does this look like in the product?
```yaml
name: my_number
  meta:
    dimension: 
      prefix: 'mega' # output would be 'mega 100' in Lightdash
```

- these values are still treated as their original type when using them/manipulating them in a results table
- if these values are used in table calculations, then their suffix is dropped. (e.g. table calculation = 'distance * 100' --> this would have no formatting applied to it)
