### ISSUE TITLE
Create dimension urls with other columns values

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3465]
### Description

The existing feature to add dimension urls can only access the value of that column. 
We should be able to access all the values in the row. 

The values should be available under `row`
eg: `row.column_name.raw` and `row.column_name.formatted`

### What problem does this solve?

This would solve the problem where I have the columns `id` and `name`, I want to make the `name` value a link using the `id` value. 

```
- name: company_id
   meta:
        dimension:
          type: number

- name: company_name
      meta:
        dimension:
          type: string
          urls:
            - label: "Open company page"
              url: "https://example.com/company/${row.company_id.raw | url_encode }"
```
