### ISSUE TITLE
Metric reference doesn't include metric filters

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3489]
### Description

Example metrics:
```
metrics:
  - name: metric1
    type: count_distinct
    filters:
      - field: is_completed
        operator: '='
        value: 'true'`
  - name: metric2
    type: number
    sql:${metric1}/100
```

The SQL generated for metric2 doesn't include the filter from metric1.

### App Version

0.284.2

**Comment by ZeRego** [comment]
@owlas In this case, if I click to view the underlying data of metric2, should it apply the filters of metric 1?

**Comment by owlas** [comment]
@ZeRego is this for dbt metrics specifically? Is this working for the new `filters:` syntax we added for `meta` metrics?

**Comment by ZeRego** [comment]
> is this for dbt metrics specifically? Is this working for the new filters: syntax we added for meta metrics?

The problem should also be present with our metric definitions.

Me and @owlas had a private conversation about this and we concluded that, based on the example given: 
- `metric2` generated SQL should contain the filter logic from `metric1`
- `metric2` doesn't inherit the filters configuration from metrics1. Meaning that when viewing the underlying data from `metric2` no filter will be applied.

**Comment by TuringLovesDeathMetal** [comment]
can we add this info to the docs? 

(once I also do this one 😅 #3535 )

**Comment by ZeRego** [comment]
Closing this issue since the SQL is being generated as intended. Feel free to reopen the issue with an example where it isn't working.

![Screenshot 2022-10-27 at 14 17 26](https://user-images.githubusercontent.com/9117144/198295010-9f340396-9514-45b7-a8ef-50d1751abe9a.png)

metrics yml:

```
  - name: completed_order_count
    label: Completed order count
    model: ref('orders')
    description: Total number of completed orders
    type: count_distinct
    sql: order_id
    timestamp: order_date
    time_grains: [day, week, month, quarter, year]
    filters:
      - field: is_completed
        operator: '='
        value: 'true'
  - name: metric2
    label: Metric2
    model: ref('orders')
    description: description metric2
    type: number
    sql: ${completed_order_count}+1
    timestamp: created
    time_grains: [ day, week, month, quarter, year ]
```

**Comment by ZeRego** [comment]
We were able to reproduce problem when using Lightdash metrics instead of dbt metrics
![Screenshot 2022-10-27 at 15 30 59](https://user-images.githubusercontent.com/9117144/198315442-88c0f2fa-0767-472e-8816-8fc9386475a7.png)

```
            marketing_arr_sold:
              type: sum
              label: aaa
              description: aaa
              model: ref('orders')
              sql: ${amount}
              format: usd
              filters:
                - is_completed: "true"
              round: 0
            percent_arr_sold_marketing:
              type: number
              label: bbb
              description: bbb
              sql: ${marketing_arr_sold}/100
              format: percent
              round: 0
```
