### ISSUE TITLE
lightdash generate should have the option to remove `dead` fields

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3516]
### Description

If you do `lightdash generate`, then there should be an option to remove columns from the YML that are no longer present in your data warehouse. 

For example, if my .yml looked like this:

```yaml
version: 2
models:
  - name: pages
    columns:
      - name: id
        description: The primary key for this table
        tests:
          - unique
          - not_null
        meta:
          metrics:
            page_view_count:
              type: count_distinct
          dimension:
            type: string
      - name: page_name
        description: my nice page
```

and my dataset in bigquery looked like this:
<img width="131" alt="image" src="https://user-images.githubusercontent.com/31848148/196472236-4ea9de2c-f023-42a7-81bb-c0335fdd2704.png">

(i.e. my `page name` column no longer exists in my bigquery dataset that `lightdash generate` is reading from)

Then, `lightdash generate` would say:

```shell
These columns in your .yml file no longer exist in your warehouse:
- page_name

Would you like to remove them from your .yml file? (y/n)
```

If the user selects `y`, then the output .yml would be:

```yaml
version: 2
models:
  - name: pages
    columns:
      - name: id
        description: The primary key for this table
        tests:
          - unique
          - not_null
        meta:
          metrics:
            page_view_count:
              type: count_distinct
          dimension:
            type: string
```

### User acceptance criteria
- [x] If I run `lightdash generate`, I'm told if there are columns which no longer exist in my data warehouse, but exist in my .yml
- [x] I'm given the option to keep or remove these columns
- [x] If a column is removed, _**all**_ of the metadata associated to that column is removed (e.g. description tests, etc.)
- [ ] If a user runs `lightdash dbt run`, then each time the `.yml` is generated, we give them the option to remove the columns that no longer exist for that model
