### ISSUE TITLE
You should be able to connect Lightdash to a dbt `target` that isn't the default in the `profiiles.yml` file.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#352]
This problem came up in the #tools-lightdash channel in dbt ([post/thread is here](https://getdbt.slack.com/archives/C026WJE4A69/p1629326382037600))

### The problem
Right now, Lightdash uses the default target defined in the dbt `profiles.yml` file. One common setup for a `profiles.yml` file is to have a `dev` target as the default and `prod` as another target option. This means that the only way to connect Lightdash to your `prod` target is by reconfiguring your `profiles.yml` file (probably not the best idea having everyone write to prod by default...so this isn't a great option...).

Here's an example of this `profiles.yml` configuration with `dev` target as default:
```
lightdash_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: lightdash-analytics
      dataset: dbt_khindson
      threads: 1
      timeout_seconds: 300
      location: us
      priority: interactive
      retries: 1
    prod:
      type: bigquery
      method: oauth
      project: lightdash-analytics
      dataset: prod
      threads: 1
      timeout_seconds: 300
      location: us
      priority: interactive
      retries: 1
 ```

### What we want to be able to do:
We want to have some way of configuring Lightdash so that it runs dbt using a different `target` than the default target defined in the `profiles.yml` file. 

### Potential solutions talked about:
- @ZeRego had one suggestion: 
> I’m wondering if we could have the option when defining the project in lightdash.yml:
> ```version: '1.0'
> 
> projects:
>   - name: default
>     type: 'dbt'
>     profiles_dir: /Users/example/.dbt
>     project_dir: /Users/example/jaffle_shop
>     target: prod
> ```
> And when we start the dbt rpc use the --target argument. 

This is a lot like the way that Fivetran solved this when they got similar feedback from users:
      - https://support.fivetran.com/hc/en-us/community/posts/1500000521381-Transformations-Allow-customization-to-the-generated-profiles-yml-for-Dbt
      - https://fivetran.com/docs/changelog/march-2021#dbttransformations
- Another option (again, credit to @ZeRego) is:
> we can take advantage of the existing profiles_dir config and have a separate folder for the profiles we want to use for lightdash.
> So we can have dbt use .dbt/profiles.yml (which is the default path ) and lightdash use .lightdash/profiles.yml
