### ISSUE TITLE
ERR_INVALID_CALLBACK

### ISSUE THREAD

**Issue by jessrosenfield** [lightdash/lightdash#3539]
### Description

```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at setInterval (node:timers:210:3)
    at Object.callback (/Users/jessica/src/coprocure/analytics/node_modules/snowflake-sdk/lib/connection/connection.js:163:26)
    at requestCallback (/Users/jessica/src/coprocure/analytics/node_modules/snowflake-sdk/lib/services/sf.js:1185:23)
    at Object.callback (/Users/jessica/src/coprocure/analytics/node_modules/snowflake-sdk/lib/services/sf.js:662:43)
    at /Users/jessica/src/coprocure/analytics/node_modules/snowflake-sdk/lib/http/base.js:111:25
    at done (/Users/jessica/src/coprocure/analytics/node_modules/urllib/lib/urllib.js:589:5)
    at /Users/jessica/src/coprocure/analytics/node_modules/urllib/lib/urllib.js:953:9
    at decodeContent (/Users/jessica/src/coprocure/analytics/node_modules/urllib/lib/urllib.js:740:14)
    at handleResponseCloseAndEnd (/Users/jessica/src/coprocure/analytics/node_modules/urllib/lib/urllib.js:924:7)
    at IncomingMessage.<anonymous> (/Users/jessica/src/coprocure/analytics/node_modules/urllib/lib/urllib.js:962:7) {
  code: 'ERR_INVALID_CALLBACK'
```

Also the "Test Adapter" step hangs pre compile when setting up existing project settings via the UI. The logs show
```
2022-10-21T16:30:38.035351+00:00 app[web.1]: 2022-10-21 16:30:38 [Lightdash] [31merror[39m: [31mUnhandled Rejection at Promise Callback must be a function. Received undefined[39m
```

### To Reproduce

Follow instructions to connect dbt to lightdash heroku deployment
run `npx lightdash deploy --create` after the login command provided by the UI for project setup

### App Version

Via heroku deploy button, 0.293.0

**Comment by ZeRego** [comment]
Hi @jessrosenfield 👋 
Can you share a redacted version of your snowflake settings? the UI form or your dbt profile yml

**Comment by jessrosenfield** [comment]
Yes I've tried a local deployment of lightdash cloud and got this error.

```
config:
    send_anonymous_usage_stats: false
    use_colors: true
    partial_parse: false

analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 8
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: [REDACTED]
      role: [REDACTED]
      warehouse: [REDACTED]
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'dbt_' ~  env_var('SNOWFLAKE_USER')) }}"
      client_session_keep_alive: True
    prod:
      type: snowflake
      threads: 8
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: [REDACTED]
      # TODO: Debug why pc_dbt_role cannot modify analytics
      role: [REDACTED]
      warehouse: [REDACTED]
      schema: [REDACTED]
```
