### ISSUE TITLE
[very small] ensure lightdash generate keeps yaml copyright notice

### ISSUE THREAD

**Issue by olly-writes-code** [lightdash/lightdash#3581]
### Description

`lightdash generate` is very useful to generate information on fields we want to show on lightdash, saving the developer from writing lots of lines of code. One pain for myself is that this function removes any copyright information in the first line. 

Example .yml
```
# Company Name, Inc. Proprietary and Confidential. Copyright 2022.

version: 2
models:
  - name: test
    columns:
      - name: id
        description: ""
        meta:
          dimension:
            type: string
```

When running `lightdash generate` this removes line 1, the copyright comment. This means that the .yml will fail our linting process.

### What problem does this solve?

Described above
