### ISSUE TITLE
I want to be able to add a description to my group_labels 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3593]
### Description

In my .yml, I'm able to add `group_labels` to my dimensions and metrics. 

I want to add a description to these group labels and have this description appear on-hover the same way that it does for dimension/metric descriptions. 

I imagine it could either live in the `model` `meta` or the `columns` `meta` tag and would work something like this:

```yaml
version: 2
models:
  - name: users_daily
        columns:
          meta:
            group_labels:
                product_usage:
                  description: "Stats on how our users are using Lightdash"
```

Then this would appear as a description on-hover of the group label (just like a metric or dimension description)
<img width="962" alt="image" src="https://user-images.githubusercontent.com/31848148/198063190-06f6c847-1ce9-40be-8401-91075a3140e5.png">

**Comment by ZeRego** [comment]
I'm inclined to have this information in the model meta. There is more information about the group that we need to store like: label, description, order, sublabels.

note: I also propose a breaking change from `group_label` to `group` since we would now use ID's instead of labels.

Proposed yml
```
version: 2
models:
  - name: users_daily
    meta:
        groups:
            - product_usage:
               label: "Product usage"
               description: "Stats on how our users are using Lightdash"
               order: 1
               sub_groups:
                  - dates:
                     label: "Product usage"
                     description: "Stats on how our users are using Lightdash"
                     order: 1
```

How to use it in dimensions:

```
  columns:
    - name: product_created_date
      meta:
        dimension:
          group_label: product_usage.dates
```
