### ISSUE TITLE
Missing `from` clause when metric filter references dimension from joined table

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3664]
### To Reproduce

1. Add metric filter that references dimension from joined table
```
            total_completed_order_amount:
              type: sum
              format: usd
              round: 2
              filters:
                - customers.first_name: "Paul"
```
2. select fields from the main table
3. run query

![Screenshot 2022-11-03 at 11 11 31](https://user-images.githubusercontent.com/9117144/199708708-8156012b-857e-4dff-89f0-a79acd7442e9.png)

### App Version

0.312.0
