### ISSUE TITLE
I want to be able to use other columns in my dimension URLs without including them in my results table

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#3669]
### Description

Right now, if I reference another column from my table in my URL, then I need to include that column in the results able for the URL to work.

E.g. I’ve added a URL to `company_name` and it uses the field `customer_id`

```
columns:
  - name: company_name
    label: Registered trading name of the company
    meta:
      dimension:
        urls:
          - label: "Open company"
            url: "https://example.com/company/${row.customers.customer_id.raw | url_encode }"
```

This will only work if I have `customer_id` in the table. (you can also see an example in this PR: https://github.com/lightdash/lightdash/pull/3467)

Ideally, this URL would work, even if we didn't have `customer_id` included in the table.

- [ ] If there were multiple customer ID options available for a single company_name, then the URL would open to another list of the many URL options. E.g. `send email` here would have an arrow, and this would open to another list of all of the potential email link options (I imagine it would just show the different values from the field, and not the different full URLs)
<img width="307" alt="image" src="https://user-images.githubusercontent.com/31848148/199751556-7bcb51ce-2b6d-41f6-901d-4573753b6327.png">
