### ISSUE TITLE
Add a `format` property to metrics + dimensions

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#372]
We have a `number` metric type, but a lot of metrics are reported in %. 

We should be able to set a `number` metric with the format `percent` (i.e. number, but take the result x 100 and stick a `%` symbol in front of it when it's rendered on the frontend)

other examples are: `gbp`, `usd`, `km`, `mi`, etc.

The way you would define these formats is in the `.yml` files:

```
columns:
  name: revenue
    meta:
      metrics:
        total_revenue:
          type: sum
          format: usd
```

In the UI, the values in the `revenue` column would now appear like:
$40.00
$567.00
etc.
