### ISSUE TITLE
Restrict access to tables based on user attributes

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#3798]
### Description

Some tables should not be accessible (queryable or searchable) by users depending on their attributes such as group/permissions/tags

The user wouldn't see these in the "Explore -> Tables" view, they would also not be able to view charts or dashboard tiles that require queries to be executed against those tables. 

So if I can't see the Users table then a chart showing "users over time" would show as unavailable.

I imagine this would look the same as user attributes applied to columns, but on a table level. E.g. 

```yaml
models:
  name: users
  meta: 
    ...
    required_attributes: 
      colour: [blue, red]
      age: 18
```

**Comment by TuringLovesDeathMetal** [comment]
**Note:** when I talk about "tables", I mean a model in dbt + any joined models using the `meta` tag in the .yml.

Here's how I'd expect joins to behave. Imagine that I have three .yml files that look like this:

**Table 1: Users**
```yaml
version: 2
models:
  - name: users
    meta:
      joins:
        - join: organizations
          sql_on: ${users.organization_id} = ${organizations.organization_id}
    required_attributes: 
      has_pii_access: 'true'
```

**Table 2: organizations**
```yaml
version: 2
models:
  - name: organizations
```

**Table 3: Tracks**
```yaml
version: 2
models:
  - name: tracks
    meta:
      joins:
        - join: tracks
          sql_on: ${users.user_id} = ${tracks.user_id}
```

As a user with `has_pii_access = false`, this is what I'll see in the UI:

**Table 1: Users**
- This table will not appear in the tables sidebar. 
- If someone else built a chart from this table, but only uses fields from the joined table `organizations`, (so, something like this: https://analytics.lightdash.cloud/share/FnG6tHpkmNXTfhVJv2XQE), I **would not have access to that chart**
- Any chart built from this table or any tables joined to it will not be available for me to explore in Lightdash (they will appear as `no access` if I open them)

**Table 2: organizations**
- This table is not affected by the access restriction. It still shows up in teh sidebar, charts built from this table are still accessible to me. 

**Table 3: Tracks**
- This table appears in the tables sidebar. 
- If I open this table in the Explore view, then the `users` model is hidden from the sidebar
- If someone else built a chart from this table, and it includes a metric or dimension from teh `users` model, then I would see a "no access" error
- If someone else built a chart from this table and it _**did not**_ include a metric or dimensions from the `users` model, I would be able to access the chart just fine.
