### ISSUE TITLE
the error message for using dimensions within a non-aggregate metric isn't clear

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#381]
How I got here...

I tried to aggregate a dimension within a non-aggregate metric definition. This failed, because non-aggregate metrics can only take in other aggregate metrics. 

^I think that this behaviour is fine: forcing people to write out metrics instead of doing dimension aggregations in the metric's sql is pretty acceptable and makes it super clear what the restrictions of these non-aggregate metrics are. It's also [clearly explained in our docs](https://docs.lightdash.com/references/metrics#:~:text=or%20integer%20value.-,It%20can%20only%20be%20used%20on%20aggregations%2C%20which%20means%20either%20aggregate%20metrics%20or%20custom%20SQL%20that%20references%20other%20metrics.,-You%20cannot%20build) that this is the behaviour to expect.

buuuuuut, it took me like 3 tries to figure out what was going wrong. 

This was the yaml I had:
```
- name: email_campaign_id
        description: The ID of the email campaign.
        tests:
          - unique
          - not_null
        meta:
          metrics:
            campaign_spam_report_rate:
              description: "Spam report rate is the ratio of emails reported as spam out of the emails that were delivered."
              type: number
              sql: "(SUM(${total_unique_spam_reports}) / NULLIF(SUM(${total_unique_deliveries}), 0))"
```

This was the error I received:
<img width="1532" alt="Screenshot 2021-08-27 at 10 34 48" src="https://user-images.githubusercontent.com/31848148/131100044-e9c0914b-1250-449c-9a10-e061c153e5dc.png">

This was the fix I needed to make:
```
- name: total_unique_spam_reports
      meta:
          metrics:
            sum_of_total_unique_spam_reports:
              type: sum

- name: total_unique_deliveries
      meta:
          metrics:
            sum_of_total_unique_deliveries:
              type: sum
  
- name: email_campaign_id
        description: The ID of the email campaign.
        tests:
          - unique
          - not_null
        meta:
          metrics:
            campaign_spam_report_rate:
              description: "Spam report rate is the ratio of emails reported as spam out of the emails that were delivered."
              type: number
              sql: "(${sum_of_total_unique_spam_reports}) / NULLIF(${sum_of_total_unique_deliveries}, 0)"
```

The error message should have a better description of what's going wrong. Specifically, it should say something about the metric that's erroring and the fact that it's a non-aggregate metric. It should potentially link to the docs if that's possible too!

e.g. 
```
Error: `campaign_spam_report_rate` is a non-aggregate metric. It can only be defined using aggregate metrics, not dimensions. See the docs for how to build non-aggregate metrics: https://docs.lightdash.com/references/metrics#non-aggregate-metrics
```
