### ISSUE TITLE
Chart as code

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#3972]
### Description

Create and update charts from YML.

### Acceptance criteria

[ ] The CLI will find charts yml inside space folders that contain `.space.yml` ( if folder doesn't have`.space.yml`, ignore those files )
[ ] chart yml contains all properties we use now (too large to document here)
[ ] resources should be created/updated when running the commands `deploy`, `preview`, `preview-start`
[ ] Migrate `saved_queries` table to have a `slug` and `project_uuid` columns with unique constrain + change space_uuid constrain to also depend on project uuid
[ ] DB changes need to be in a single transaction

Example folder structure:
```
lightdash
└── spaces
    ├── marketing
    │   ├── .space.yml
    │   └── daily-users-count.yml
    └── sales
        ├── .space.yml
        └── daily-revenue.yml
```

Example `daily-users-count.yml`:

```
resource: v1/charts

slug: my-chart
name: My chart
description: My chart description
explore: users
query:
  dimensions:
    - one
    - two
  metrics:
    - three
    - four
  filters:
    - (horrible api)
  sorts:
    - field: 5
      descending: true
  limit: 100
  tableCalculations:
    - name: my
      displayName: another
      sql: horrid

pivotConfig:
  columns: [my-pivot-dim]

chartConfig:
  type: cartesian
  layout:
  echartsConfig:
```

### Technical implementation

1. CLI gets all the resources info and sends to BE endpoint
2. BE converts those objects to latest type and saves in DB
