### ISSUE TITLE
Add ability to order dimensions based on yml (i.e. override the Alphabetical default)

### ISSUE THREAD

**Issue by olly-writes-code** [lightdash/lightdash#4000]
### Description

Pretty self-explanatory!

### What problem does this solve?

It improves user experience, often, primary keys are the first columns in a table, and categories or booleans are often further down.

Maybe this has been experimented with! Curious to hear your thoughts.

### Acceptance criteria

- [ ] There is a setting in the model meta for the field ordering to be applied to the Lightdash sidebar

For example, something like this: (I'm not sure if `yml` is the clearest name for the option where it follows the order in the .yml. Maybe `raw` or something instead?):
```
version: 2
models:
  - name: organizations_daily
    meta:
      field_order: yml # the other option is `alphabetical`, which is the default value
```

- [ ] if there are group_labels, then the group label appears in the order where it first appears in the .yml (and the fields within the group label appear in the order they appear in the .yml). For example:
```
- name: product_id
- name: user_id
  meta:
    dimension:
        group_label: users
- name: revenue
- name: user_location
  meta:
      dimension:
         group_label: users
```

Would appear in the sidebar like:

- product_id
- Users:
    - user_id
    - user_location
- revenue

- [ ] if the `yml` option is selected, then metrics also appear in the metrics list in the order that they appear in the .yml

**Comment by owlas** [comment]
Great suggestion @olly-writes-code. @TuringLovesDeathMetal I feel like this is something we've discussed before?

I think a current workaround that folks use is (and don't laugh) use a custom label and prepend whitespace:


```yaml
columns:
  - name: column_that_should_be_first
    meta:
      label: '   My first column'
```
