### ISSUE TITLE
Closing bracket for sum metric is getting put in the wrong place

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4025]
### Description

Here's the .yml:

```
            average_order_value:
              type: number
              description: 'average order value (excluding VAT after discount)'
              sql: " ${total_revenue_exc_vat} / ${total_order_count} "
```

here's the compiled SQL:
```
SELECT
  `OrderLines`.tax_percent AS `OrderLines_tax_percent`,
  SUM( (`OrderLines`.TOTAL_GBP_after_vouchers-`OrderLines`.tax_amount) / COUNT(`OrderLines`.order_id) ) AS `OrderLines_average_order_value`
FROM `datawarehouse-358408`.`magento`.`OrderLines` AS `OrderLines`

GROUP BY 1
ORDER BY `OrderLines_average_order_value` DESC
LIMIT 500
```

You can see, the `SUM()` closing bracket is wrapped around the entire query. It should only be wrapped around the numerator (since `total_revenue_exc_vat` is = `SUM(`OrderLines`.TOTAL_GBP_after_vouchers-`OrderLines`.tax_amount)`)

The actual SQL should be:
```
SELECT
  `OrderLines`.tax_percent AS `OrderLines_tax_percent`,
  SUM(`OrderLines`.TOTAL_GBP_after_vouchers-`OrderLines`.tax_amount) / COUNT(`OrderLines`.order_id) AS `OrderLines_average_order_value`
FROM `datawarehouse-358408`.`magento`.`OrderLines` AS `OrderLines`

GROUP BY 1
ORDER BY `OrderLines_average_order_value` DESC
LIMIT 500
```
