### ISSUE TITLE
Invalid alias name for nested column in BigQuery

### ISSUE THREAD

**Issue by pilis** [lightdash/lightdash#4097]
### Description

I've tried adding a dimension to an explore that is a nested column in BigQuery. In dbt properties file nested columns are registered using "dot" syntax in the format: `group.column` (dot in-between). When Lightdash compiles the query it's using exact dimension name to make an alias in the format: `table_dimension` (underscore in between). For nested columns in BigQuery it gives: `table_group.column` (first underscore then dot). That's invalid column alias in BigQuery according to error message: `Invalid field name "table_group.column". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 300 characters long.`

### To Reproduce

1. Create a table in BigQuery with a nested column
2. Create respective Ligthdash model in dbt
3. Try to create an explore with nested column dimension
4. You should receive an error: `Invalid field name "table_group.column". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 300 characters long`

### App Version

0.361.0

**Comment by pilis** [comment]
I have traced the error down to https://github.com/lightdash/lightdash/blob/main/packages/backend/src/queryBuilder.ts#L72 where I could simply substitute a dot in `alias` variable, but I don't know what implications it will give on frontend yet since there is some variables binding implemented and I lack front-end skills

**Comment by TuringLovesDeathMetal** [comment]
Hey @pilis thanks for opening this issue and for all of the great details in here!

We'll take a look at it and see what we can do 👀

**Comment by ZeRego** [comment]
This means we need to change how we create the field ids. Not sure what side effects this may cause 🤔.

_packages/common/src/types/field.ts_
```
export const fieldId = (field: Pick<Field, 'table' | 'name'>): FieldId =>
    `${field.table}_${field.name}`;
```

**Comment by TuringLovesDeathMetal** [comment]
@pilis for now, you'll need to flatten the table in dbt to use nested fields in Lightdash. We have a related issue here: #4102 where we talk about a potential solution, but were not going to focus on it for this quarter (we definitely want to improve how we handle nested fields in the future though!)

So, for your example column, you'd need to make it into a field in your dbt model, like:

```sql
SELECT
field.name AS field_name

FROM table
```

Then you could access the field in Lightdash in your .yml

**Comment by pilis** [comment]
@TuringLovesDeathMetal Fair enough! 

This workaround is valid, but I had a hope that it would be easy enough to support nested fields and not to flatten wide tables (100s of columns). 

I think I can try digging more and figuring out what are the implication and hopefully submit Pull Request 😊 It should take shorter than generating flattened models and should pay off in the longer run 🙂

**Comment by yu-iskw** [comment]
I have the same issue.

**Comment by ZeRego** [comment]
example of how users currently declare these columns in yml 
```
columns:
  - name: struct_column1.a
    meta:
      dimension:
        type: string
  - name: struct_column2.nested_struct.b
    meta:
      dimension:
        type: number
```

**Comment by yu-iskw** [comment]
Thank you for resolving it. I made sure even deeply nested STRUCT data type in BigQuery works at v0.671.0 on Lightdash Cloud.

![image](https://github.com/lightdash/lightdash/assets/1523515/4b7ff48f-60bb-4a76-97d9-f5a833732774)


## dbt mode
I created a subsequent dbt model to make sure if deeply nested STRUCT data type works. 
```
SELECT
   1 AS scalar_number,
   "x" AS scalar_string,
   STRUCT(
     1 AS simple_struct_number,
     "x" AS simple_struct_string
   ) AS simple_struct,
   STRUCT(
     STRUCT(
       1 AS simple_struct_number,
       "x" AS simple_struct_string
     ) AS simple_struct
   ) AS nested_struct,
```
The corresponding schema YAML is like below. 
```yaml
version: 2
models:
  - name: test_lightdash
    columns:
      - name: scalar_number
        description: ""
        meta:
          dimension:
            type: number
      - name: scalar_string
        description: ""
        meta:
          dimension:
            type: string
      - name: simple_struct
        description: ""
        meta:
          dimension:
            type: string
      - name: simple_struct.simple_struct_number
        meta:
          dimension:
            type: number
        description: ""
      - name: simple_struct.simple_struct_string
        meta:
          dimension:
            type: string
        description: ""
      - name: nested_struct
        description: ""
      - name: nested_struct.simple_struct
        description: ""
      - name: nested_struct.simple_struct.simple_struct_number
        description: ""
      - name: nested_struct.simple_struct.simple_struct_string
        description: ""
```
