### ISSUE TITLE
I want to specify a set of `show underlying values` to use by default in a table. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4100]
### Description

if in the meta: at the table level, you could alias 'underlying value lists'. and set one as default.

That way we can set our own defaults instead of having lightdash choose all the columns.

and when you go to add underlying values to 10 different metrics, you can just specify the 'set' rather than copy and pasting the list 10 times. 

For example, something like:

```
version: 2
models:
  - name: slurpee_feature_releases
    meta:
      show_underlying_values_lists:
        users_list: 
          values: ['user_id', 'user_activated_date', 'user_name', 'user_type'] 
          default: true
        companies_list: 
          values: ['company_id', 'company_activated_date']
    columns:
      - name: user_id
        meta:
          metrics:
            count_distinct_user_id:
              type: count_distinct
              show_underlying_values: 
                - list: 
                    users_list # I'm not sure how we could get a mix of lists and single fields in here (maybe someone has some better YAML syntax sugestions)
                - revenue_gbp_total_est
                - actual_date
                - web_sessions.session_id
```

### What problem does this solve?

It's really annoying/time consuming to repeat the same underlying values for all of the metrics in a table. 

### Acceptance criteria:

- [ ] I'm able to define lists of underlying values for a table
- [ ] I'm able to use these lists in my underlying values specification for a metric
- [ ] I'm able to define a list as `default` in my meta by setting `default: true`
- [ ] If I define a list as `default`, then it will be applied as the default list to all of my metrics unless I specify a different list
- [ ] `default` is FALSE by default
- [ ] I'm able to specify a list and also add other fileds to the `show underlying values` for a single metric
