### ISSUE TITLE
I want to create a `median` metric in Lightdash

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4119]
### Description

This is a follow-up from #4103 . Instead of making people use `percentile` to calculate a median, let's just add a median option. 

### What problem does this solve?

Some people won't be familiar with percentiles, but will be familiar with medians. 

### Acceptance criteria

- [ ] I'm able to create a metric of type `median` in my yaml
- [ ] the median is just the 50th percentile

### Suggested solution

```yaml
- name: cost
    meta:
      metrics:
        median_cost:
          type: median
```

Which would just compile `PERCENTILE_CONT(cost, 0.5) OVER()`
