### ISSUE TITLE
Metric filter does not work for NULL values

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4334]
### Description

I want to add `is equal to null` to my metric filters: https://docs.lightdash.com/references/metrics#available-filter-types

So, I try adding it like this:

```yml
missed_hours_unknown_reason:
  label: Hours - Without Parent Note
  type: sum
  filters:
    - explanation_source: null
```

But, the filter doesn't work. 

I want to be able to use metric filters for `NULL` and `!NULL`
