### ISSUE TITLE
Only required project settings can be set via environment variables

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#434]
Example:

```
// lightdash.yml
version: '1.0'
mode: default
projects:
  - name: default
    type: 'dbt'
    profiles_dir: /.dbt
    project_dir: /jaffle_shop
    target: dev
```

```
// env 
LIGHTDASH_PROJECT_0_PROFILES_DIT=/usr/ap/profiles
LIGHTDASH_PROJECT_0_TARGET=prod
```

Lightdash recognises `LIGHTDASH_PROJECT_0_PROFILES_DIT` value but not `LIGHTDASH_PROJECT_0_TARGET`

Looking at the code in `packages/backend/src/config/parseConfig.ts` we can see that we only check env vars for the required fields. 
In this case, `target` is an optional setting so it's not recognised.
