### ISSUE TITLE
Document how to order fields

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4353]
**Link to existing docs:** 

**Changes?**

Document changes from #4345

Example yml:
```
models:
  - name: customers
    meta:
      order_fields_by: index // or 'label'
```
      
We went with index and label instead of yml and alphabetically because this opens the possibilities for future order options. eg: type, name

Notes on the order logic:

- since metrics can be declared in multiple places we forced the following order: dbt metrics > metrics in model metadata > metrics in dimension metadata
- group labels inherit the index of the first dimension that uses it
- fields order defaults to label
