### ISSUE TITLE
Unhelpful error messages when referencing metrics in an aggregate metric

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4387]
### Description

The problem is that aggregate metrics ( eg: SUM ) can only reference dimensions and non-aggregate metrics (eg: number) can only reference metrics.
Docs:
https://docs.lightdash.com/references/metrics#aggregate-metrics

The error messages should explain that instead.

### To Reproduce

```
  - name: amount
        meta:
          dimension:
            type: number
          metrics:
            avg_tutition_fee_without_10k:
              type: average
              filters:
                - amount: ">10000"
            scholarschip_cash_in:
              type: sum
              label: Scholarship In
              sql: "if(${avg_tutition_fee_without_10k} < ${amount},  ${amount} - ${avg_tutition_fee_without_10k}, NULL)"
```
Error: 

Model “tuition_fees” has a dimension reference: ${avg_tutition_fee_without_10k} which matches no dimension`

### App Version
0.404.0
