### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by swiftsam** [lightdash/lightdash#4552]
### Description

We updated from 0.405.1 to 0.418.1 and our github action deployments of our dbt project to lightdash began failing with the openSSL error, 
`error:0308010C:digital envelope routines::unsupported`.

Updating to 0.426.1 (current) results in the same behavior. 

We attempted to roll back to 0.405.1 to confirm the cause of the issue, but were unable to do so because of db migrations between those versions. 

We are able to deploy using the UI.  

### To Reproduce

```
cd dbt
  lightdash deploy --target prod --select tag:lightdash
  shell: /usr/bin/bash -e {0}
  env:
    DBT_PROFILES_DIR: /home/runner/work/grebe/grebe/.github/config
    DBT_ARTIFACT_STATE_PATH: /home/runner/work/grebe/grebe/dbt/prod-run-artifacts
    SNOWFLAKE_PRIVATE_KEY_PATH: /home/runner/work/grebe/grebe/svc_user.p8
    LIGHTDASH_URL: ***
    LIGHTDASH_PROJECT: c[3](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:3)3b0636-11b0-[4](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:4)e1e-877e-e8e46916[5](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:5)384
    LIGHTDASH_API_KEY: ***
    pythonLocation: /opt/hostedtoolcache/Python/3.9.1[6](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:6)/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.16/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.16/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.16/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.16/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.16/x64/lib
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    SNOWFLAKE_PRIVATE_KEY_PASS: ***
(node:1864) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/[7](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:7)PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Warning: CLI (0.426.2) is running a different version than Lightdash (0.426.1) on ***.
         Some commands may fail, consider upgrading your CLI by doing: npm install -g @lightdash/cli@0.426.1
20:01:05  Running with dbt=1.3.2
20:01:05  Partial parse save file not found. Starting full parse.
20:01:29  Found 646 models, [8](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:8)06 tests, 0 snapshots, 0 analyses, 78[9](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:9) macros, 1 operation, 3 seed files, 328 sources, 0 exposures, 0 metrics
20:01:29  
20:01:39  Concurrency: 8 threads (target='prod')
20:01:39  
20:01:42  Done.

error:03080[10](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:10)C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
    at Object.createPrivateKey (node:internal/crypto/keys:632:[12](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:12))
    at new SnowflakeWarehouseClient (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@lightdash/warehouses/dist/warehouseClients/SnowflakeWarehouseClient.js:[13](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:13)0:45)
    at warehouseClientFromCredentials (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@lightdash/warehouses/dist/warehouseClientFromCredentials.js:[14](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:14):20)
    at /usr/local/lib/node_modules/@lightdash/cli/dist/handlers/compile.js:[15](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:15)2:83
    at step (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/compile.js:67:23)
    at Object.next (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/compile.js:48:53)
    at fulfilled (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/compile.js:39:58) {
  opensslErrorStack: [ 'error:0308010C:digital envelope routines::unsupported' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Error: error:0308010C:digital envelope routines::unsupported
    at Object.createPrivateKey (node:internal/crypto/keys:632:12)
    at new SnowflakeWarehouseClient (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@lightdash/warehouses/dist/warehouseClients/SnowflakeWarehouseClient.js:130:45)
    at warehouseClientFromCredentials (/usr/local/lib/node_modules/@lightdash/cli/node_modules/@lightdash/warehouses/dist/warehouseClientFromCredentials.js:14:[20](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:20))
    at /usr/local/lib/node_modules/@lightdash/cli/dist/handlers/compile.js:152:83
    at step (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/compile.js:67:[23](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:23))
    at Object.next (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/compile.js:48:53)
    at fulfilled (/usr/local/lib/node_modules/@lightdash/cli/dist/handlers/compile.js:[39](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:40):[58](https://github.com/ArcadiaPower/grebe/actions/runs/4236368401/jobs/7361118940#step:10:59))
```

### App Version
first observed in 0.418.1, still present in 0.426.1

**Comment by owlas** [comment]
Hey @swiftsam are you able to share your GitHub actions file that's being used to deploy?

**Comment by swiftsam** [comment]
Sure, it looks like this. Now I'm worried this is on our side not a lightdash issue, but no changes to this file in the last 2 weeks

```yaml
name: lightdash-deploy

on:
  # Triggers workflow when we merge code to main
  push:
    branches: [ "main" ]
    paths: ['dbt/**.yml']
  workflow_dispatch:

jobs:
  metadata:
    uses: ./.github/workflows/metadata.yml

  deploy:
    runs-on: ubuntu-20.04
    # Required for JWT token swap in aws-actions/configure-aws-credentials@v1
    permissions:
      id-token: write
      contents: read
    needs: [metadata]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.metadata.outputs.python_version }}

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GREBE_MAIN_GHACTIONS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      # TODO: Refactor to use Docker image with pre-installed dependencies
      - uses: actions/cache@v3
        id: python-cache
        with:
          # We cache our entire python environment to save on both download and install (wheels) time
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles(needs.metadata.outputs.python_requirements_path) }}

      - name: Install pip requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r ${{ needs.metadata.outputs.python_requirements_path }} --extra-index-url https://${{ secrets.GEMFURY_TOKEN }}:@pypi.fury.io/arcadiapower/
      - name: Set snowflake authentication
        run: |
          SNOWFLAKE_PRIVATE_KEY_PASS=$(aws ssm get-parameter --name /snowflake/svc_user/production/PRIVATE_KEY_PASSPHRASE --query 'Parameter.Value' --output text)
          echo "::add-mask::$SNOWFLAKE_PRIVATE_KEY_PASS"
          echo "SNOWFLAKE_PRIVATE_KEY_PASS=$SNOWFLAKE_PRIVATE_KEY_PASS" >> $GITHUB_ENV
          aws ssm get-parameter --name /snowflake/svc_user/production/PRIVATE_KEY --query 'Parameter.Value' --output text > "${{ env.SNOWFLAKE_PRIVATE_KEY_PATH }}"
      - name: Install dbt dependencies
        run: dbt deps
        working-directory: ${{ needs.metadata.outputs.dbt_project_dir }}

      - name: Install Lightdash CLI
        run: npm i -g @lightdash/cli

      - name: lightdash deploy
        run: |
          cd dbt
          lightdash deploy --target prod --select tag:lightdash
    env:
      DBT_PROFILES_DIR: ${{ needs.metadata.outputs.dbt_profiles_dir }}
      DBT_ARTIFACT_STATE_PATH: ${{ needs.metadata.outputs.dbt_project_dir }}/prod-run-artifacts
      SNOWFLAKE_PRIVATE_KEY_PATH: ${{ github.workspace }}/svc_user.p8
      LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}
      LIGHTDASH_PROJECT: c33b0636-11b0-4e1e-877e-e8e469165384
      LIGHTDASH_API_KEY: ${{ secrets.LIGHTDASH_API_KEY }}
```

**Comment by ZeRego** [comment]
> Reason For The Error
> In Node.js v17, the Node.js developers closed a security hole in the SSL provider. This fix was a breaking change that corresponded with similar breaking changes in the SSL packages in NPM. When you attempt to use SSL in Node.js v17 or later without also upgrading those SSL packages in your package.json, then you will see this error.

https://stackoverflow.com/a/73027407

Error origin: `crypto.createPrivateKey(...)` in `SnowflakeWarehouseClient`

We haven't changed the dependencies involved or code recently. We should be able to reproduce the error if we try to run the CLI with node18

**Comment by ZeRego** [comment]
@swiftsam can you try pinning the node version at the top?
Example:
```
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '16'
```
