### ISSUE TITLE
How to enable the scheduler worker when self hosting Lightdash 

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#4577]
**Link to existing docs:** 

**Changes?**

I just noticed that we lack documentation on how to setup the scheduler worker for self-hosted users and that’s why is not sending emails.
Self hosted users can run the schedule worker in 2 different ways:
- add the env variable `SCHEDULER_ENABLED=true`. In this option the scheduler worker is going to run in the same container as the Lightdash server.
- or, have a dedicated docker container to run the worker. This option is a more advanced setup so users can better configure the scalability of their containers.
```
// in your docker-compose.yml  
  scheduler:
    image: lightdash/lightdash:latest
    entrypoint: ["yarn", "workspace", "backend", "scheduler"]
    depends_on:
      - db
    environment:
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE:-postgres}
      - LIGHTDASH_SECRET=${LIGHTDASH_SECRET}
```
