### ISSUE TITLE
I want to be able to hide my joined models in my .yml

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#4596]
### Description

Sometimes, you need to use an intermediate model to join two models together. 

For example, here, I'm using model B to join Model C to model A.

```
models:
- name: A
  meta:
    joins:
    - join: B
      sql_on: B.a_id = A.a_id
    - join: C
      sql_on: C.b_id = B.b_id
```

Sometimes, I only care about model C being shown in the explore (model B is really only being used for joining the two together). 

I want to be able to hide model B. 

We could add a `hidden: true` tag to joins, like this:

```
models:
- name: A
  meta:
    joins:
    - join: B
      sql_on: B.a_id = A.a_id
      hidden: true
    - join: C
      sql_on: C.b_id = B.b_id
```

### Acceptance criteria

- [ ] I'm able to hide joined models from an explore
- [ ] the joined models are still compiled in Lightdash
- [ ] the joined model needs to be included in the list of models "available" in Lightdash (i.e. must be included in the tables list in the project settings) - we can change this if people need it to be _**not**_ from the list of models in the project settings later
- [ ] if a joined model is hidden, then it does not appear in teh explore sidebar
- [ ] if a joined model is hidden, the fields from that joined model are still "available to use" in the .yml (for example, in custom SQL for a metric, in join logic for another model)

### Documentation

ADd docs to the `joins` reference doc here: https://docs.lightdash.com/references/joins
