### ISSUE TITLE
misleading error message @ misformatted yml config 

### ISSUE THREAD

**Issue by halacsy** [lightdash/lightdash#4720]
### Description

I've accidentally wrote a not valid metrics definition in an `yml` file

```
      - name: amount
        description: ""
        meta:
          dimension:
            type: number
          metrics:
            total: sum
```
instead of 
```
      - name: amount
        description: ""
        meta:
          dimension:
            type: number
          metrics:
            total:
              type: sum
```

and I got an error message saying: `- ERROR> consolidated_report : Cannot read properties of undefined (reading 'toUpperCase')`.  I think yml file should be validated first.

### To Reproduce

1. create dimension
2. add metrics like the one above.

### App Version

```
lightdash --version
0.409.0
```
