### ISSUE TITLE
A usage_description field

### ISSUE THREAD

**Issue by Martin-Carlsson** [lightdash/lightdash#4888]
### Description

A `usage_description` field on table level that takes markdown.

### What problem does this solve?

We like to give people access to as much as possible. However, this means that they click around and start using models in ways they weren't intended for.

I would like a way to communicate with users on how to use the specific model.

The `description` field is for describing the model, plus we can't expect users to hover over the table.

### Idea for implementation

```
models:
  - name: lightdash_finance_mart_montly_revenue
    description: "Revenue on a monthly basis"
    meta:
      label: "Finance mart | Revenue monthly"
      usage_description: "**Important!** This data can only be used on a monthly basis."
    columns:
      - name: company
        meta:

...
```

<img width="394" alt="image" src="https://user-images.githubusercontent.com/7769335/226794911-1896f6b8-2ba3-45da-b578-7cc9b74c1ff6.png">
