### ISSUE TITLE
Metric with multiple filters values generates unexpected SQL

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#5048]
### Description

Metric with multiple filters values generates unexpected SQL

Here's an example of yaml config - metric with filters:

```
...
  n_status_xy:
    type: count_distinct
    filters:
      - status_field: 
          - status_x
          - status_y
...
```

generated sql:

`... COUNT(DISTINCT CASE WHEN ((status_field) IN ('status_x,status_y') ...`

expected sql:

`... COUNT(DISTINCT CASE WHEN ((status_field) IN ('status_x','status_y') ...`
