### ISSUE TITLE
Support dbt doc references in metric description

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#5169]
### Description

```
      - name: count
        meta:
          metrics:
            count_example:
              type: sum
              description: '{{ doc("field_count_example") }}'
```

The docs references are handled by dbt CLI and they don’t check for it in the meta properties. :disappointed:

Lightdash should handle the doc reference.

### What problem does this solve?

Be able to centralize all the descriptions in a `.md` file and keep the yml clean.
