### ISSUE TITLE
Lightdash.yml should be valid without any projects

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#520]
I tried using the following `lightdash.yml` and got an error

```yaml
# lightdash.yml
version: '1.0'
mode: cloud_beta
projects:
```

gave me

```
ParseError: Lightdash config file successfully loaded but invalid: Project index: 0 must have personal_access_token or environment variable LIGHTDASH_PROJECT_0_PERSONAL_ACCESS_TOKEN.
```

I expected this to work since I no longer need to provide any projects on initial server creation
