### ISSUE TITLE
Cannot read properties of undefined (reading 'toUpperCase') 

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#5394]
### Description

![image](https://user-images.githubusercontent.com/1983672/236763177-663292d1-8fd4-4ea0-b3ee-425c51c3eff4.png)

yaml: 

```
metrics:
  - name: conversion_percent
    label: Conversion Percent
    model: ref('monthly_referral_conversion')
    description: "(Registrations/Leads Allocated) x 100"
    calculation_method: average
    expression: conversion_percent
    timestamp: lead_createdon
    time_grains: [day, month, year]
    dimensions:
      - Center
      - Team
      - Product
      - lead_createdon
      - salesdate_date
```

on Bigquery warehouse 

more details in thread  https://lightdash-community.slack.com/archives/C03MG2VTR08/p1683529403288019
