### ISSUE TITLE
Keep original quotations and comments in generated property YAML files

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#5422]
### Description
`lightdash generate` is awesome to automatically add metadata for lightdash. But, it can be break YAML files, if they contains prohibit characters without quotations as `[` and `]`. Aside from that, we would like to keep comments in original YAML files in the generated YAML files.

#### Example YAML
If the original looks like below,
```yaml
  columns:
    # The column will be deprecated on xxx.
    - name: column1
      description: "Acceptable only [1, 2, 3]"
```

the generated YAML is invalid because `[` and `]` is 
```yaml
  columns:
    - name: column1
      description: Acceptable only [1, 2, 3]
```

### What problem does this solve?

In python, there is a package which enables us to keep comments and quotations in an original YAML. However, I don't know if there is any similar module which is available in node for the lightdash CLI.
https://pypi.org/project/ruamel.yaml/
