### ISSUE TITLE
Specific multiple values in metric filters

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5485]
### Description

When adding filters to metrics you can only filter to a single value e.g.:

```
metrics:
  my_metric:
    type: count
    filters:
      - tag: 'red'
```

I'd like to be able to provide multiple values that are combined with an `OR`

```
metrics:
  my_metric:
    type: count
    filters:
      - tag: 'red,blue'
```
