### ISSUE TITLE
Lightdash generate removes inline comments in my .yml

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5707]
whenever I run lightdash dbt run --select <model_name> , the comments which I have/had saved in the yml are no longer there.
note: I am commeting by appending a #  to a line e.g. see the # round: 2  here:

```
          sum(${TABLE}.members_verified) )
          group_label: Aggregated Rates
        
        high_scoring_fraud_members_rate:
          label: High Scoring Fraud Rate
          description: members with stellar fraud score of 0.8 or higher / registered members
          type: number
          format: percent
          # round: 2
          sql: div0( sum(${TABLE}.high_risk_verified_members) , sum(${TABLE}.members_verified) )
          group_label: Aggregated Rates

        member_score_a_rate:
          label: Member Score A Rate
```

### Acceptance criteria

- [ ] lightdash generate should not remove inline comments
