### ISSUE TITLE
Create "virtual" dimensions in dbt yaml, which can be built on one or many columns

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5737]
### Description

Currently we have one dimension per documented column in a dbt model.

Sometimes we don't want to modify the underlying dbt model in order to add a dimension in the UI (usually because it's specific only to the viz layer). I'd like the ability to create my own dimensions on the model, which aren't materialized in the dbt model, only at run time (I call them _virtual_ dimensions 👾 )

```yaml
models:
  - name: users
    meta:
      dimensions:
        my_virtual_dimension:
          sql: 'IF(${TABLE}.user_id is null, 1, 2)'
```
