### ISSUE TITLE
Control access to fields based on user attributes (aka column-level-security)

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#5741]
### Description

In order to hide sensitive data from certain users, we want to be able to control access to certain fields in the model. We can do this based on the attributes that the user has:

```
columns:
  - name: secret_salary
     meta:
       dimension:
          required_attributes:
            can_view_financial_data: "true"
            team: "product"
```

### Restricting access

If the user doesn't have all the required_attributes then they won't see the field in the sidebar when exploring and any query involving that field should throw a forbidden error. 

Note the user could get access if they have sql runner access or we introduce custom dimensions. 

### Analytics events

-  add this to the `project_compile` event. E.g. `column_access_filters_count`

### Documentation

- add column-based security access to the dimension reference docs: https://docs.lightdash.com/references/dimensions
- add `column access filters` to the "where can attributes be used?" in the user attributes docs: https://github.com/lightdash/lightdash/issues/6246
