### ISSUE TITLE
A metric (with one of the existing types) can be built from other metrics

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#58]
Right now, we can only build metrics from dimensions. This limits the types of metrics that you can build/the things you can calculate in lightdash.

- We should be able to define a metric with one of the existing types using other metrics and dimensions. 
- These other metrics come from the current model, or any metrics in a joined model

I'd imagine it would look something like this in the .yml file:
```
    columns:
      - name: user_id
        description: 'Unique identifier for a user.'
        tests:
          - unique
          - not_null
        meta:
          metrics:
            num_unique_users:
              type: count_distinct
            num_unique_7d_web_active_users:
              type: count_distinct
              sql: "IF(${is_7d_web_active}, ${user_id}, NULL)"
            num_unique_non_7d_web_active_users:
              type: sum
              sql: "${num_unique_users} - ${num_unique_7d_web_active_users}" # both are metrics coming from the base model
     - name: is_7d_web_active
        meta:
          metrics:
            avg_spend_per_7d_web_active_user:
              type: mean
              sql: "IF(${is_7d_web_active}, ${transactions.total_spend}, NULL" # this is an example where the transactions.total_spend is a metric that is coming from a joined model: transactions. 
```

**Comment by owlas** [comment]
You're referring to the "non-aggregate" measure types in Looker rather than the "post-sql" measures (aka table calculations).

https://docs.looker.com/reference/field-reference/measure-type-reference#measure_type_categories

**Comment by owlas** [comment]
## Example of a single aggregate measure:

### Input schema
```yaml
# schema.yml
meta:
  metrics:
    my_metric:
      type: sum
      sql: somesqlstring
```

### Output sql
```sql
SELECT ..., SUM(somesqlstring) AS my_metric
FROM table
```

## Example of a non-aggregated derived metric

### Input schema
```yaml
# schema.yml
meta:
  metrics:
    my_metric_plus_two:
      type: number
      sql: 2 + ${myMetric}
```

### Output sql
```sql
SELECT ..., SUM(somesqlstring) AS my_metric, 2 + SUM(somesqlstring) AS my_metric_plus_two
FROM table
```
