### ISSUE TITLE
"Could not parse dbt metric with id ...: Field at "/timestamp" must be string"

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5826]
### Description

I am running into an error while exposing a metric to Lightdash.
The error states "Could not parse dbt metric with id metric.number_of_days: Field at "/timestamp" must be string"
The metric is a count_distinct on a timestamp field. I tried to cast the timestamp field as string, still facing the same issue.
metric definition in yml is :
```
- name: number_of_days
    label: number of days
    model: ref('order')
    calculation_method: count_distinct
    expression: order_created_date_str
    config:
      enabled: true
```
The metric works fine in DBT preview.

(more details in Slack thread here: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1686075043734569)
