### ISSUE TITLE
Should you be able to define dimensions in Lightdash that don't exist in your underlying data models?

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#597]
### Context
Right now, we have made defining dimensions quite strict in Lightdash: a dimension _**must**_ be a column in your underlying data model. It can't be defined in Lightdash/in the `meta` of a models' `.yml` file --> it has to be defined in your dbt model `.sql` file. 

### Goal
Let's talk about this. 

What are the positives to this approach? 
What are the negatives to this approach? 
Do you think we should be taking a different approach?

**Comment by owlas** [comment]
> guarantee that a properly configured view would work properly

We should definitely keep this in mind as it helps keep queries fast and cheap

**Comment by TuringLovesDeathMetal** [comment]
Here's another example we ran into: age brackets/bands. 

I want to group my ages, or revenue, or some other field into buckets. But, to do that, I need to actually add a dimension to my underlying data model 🤮 

What if I'm trying to figure out which bucketing is best for my visualization? Having to run the underlying data model each time to do this would be a terrible experience. 

Instead, we could have two things: 

1. "You can have multiple dimensions defined for a single field in your dbt model"

This would look something like this in your .yml:

```
name: column_name
meta:
  dimensions:
    dimension_name_one:
      type: number
      label: "Day of Week"
      sql: "day_of_week(${column_name})"
    dimension_name_two:
      type: boolean
      label: "Weekday or Weekend"
      sql: "case when day_of_week(${column_name}) < 5 then 'weekday' else 'weekend' end"

name: another_column_name
meta:
  metrics:
    metric_name_one:
      type: sum
      label: "Total sales (USD)"
    metric_name_two:
      type: average
      label: "Average sales (USD)"
```

2. "You should be able to create on-the-fly dimensions in the UI"

This would let you do more one-off analyses or explorations. It would also solve issues like this: https://github.com/lightdash/lightdash/issues/2699#issue-1303433573

This would look like custom metrics, except you'd have a box where you could write the SQL. These would be _**different**_ to custom metrics (since they would actually be calculated in a different place in the query (I think?))
