### ISSUE TITLE
Error message for missing quotes in metric + dimension parameters is not helpful

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#5993]
### Description
I have YAML that looks like this: 
```
 avg_certs_graded_per_hour:
              label: Average Number of Certs Graded per Hour
              sql: "(${num_certs_graded}/nullif(${work_hours},0))"
              format: number --- this should be "number" instead of number
              round: 1
```
got me:
`- ERROR> psa_grader_throughput : Cannot read properties of undefined (reading 'toUpperCase')`

I would expect something like `format values must be encased by quotes` or something.
