### ISSUE TITLE
The `label` parameter in Lightdash meta should take priority over the `label` used in the dbt metrics definition.

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#6162]
### Description

When implementing our metrics in DBT and Lightdash we run into the following problem:
Different tables (lets say concerning a different product) both report on a (sales) metric.
If we would label both metrics Sales in the metrics we define (DBT structure), Lightdash shows a nice Sales label in both tables! 
However, this results in duplication in our DBT docs 
We would like to label our metric in DBT as: {{column}}_{{calculation_method}}_{{table}} to better distinguish the different metrics in our docs (and stay true to snake_case)
However, this would result in ugly and unnecessary long snake case labels in our Lightdash instance, e.g. bad user experience.
I tried relabelling the metrics in Lightdash using the meta: configuration, however this did not work.
Example of what would work for us:
```
metrics:
  - name: sales_summed_product2
    label: sales_summed_product2
    model: ref('product2')
    calculation_method: sum
    expression: sales
    timestamp: date
    time_grains: [day, week, month, quarter, year]
    dimensions:
      - interesting_dimension1
      - interesting_dimension2
      - interesting_dimension3
    meta:
      metrics:
         label: Sales
```

This doesn't work right now because Lightdash uses the `label` from the dbt metric as a label in Lightdash (instead of using the `meta: ` label.

The Lightdash `meta: label:` parameter should take priority over the dbt metrics `label` parameter.
