### ISSUE TITLE
`sql_on` can reference user attributes

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6413]
### Description

I want to be able to reference user attributes in `sql_on`:

```yaml
models:
  - name: users
    meta:
      joins:
        - join: events
           sql_on: ${users.user_id} = ${events.user_id} AND ${users.email} = ${lightdash.user.email}
```
