### ISSUE TITLE
Make location of BigQuery connection optional

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#6635]
### Description
The location of a BigQuery connection is required on Lightdash. However, the `location` configuration is optionla. 

![image](https://github.com/lightdash/lightdash/assets/1523515/c1fc31c5-d4ef-4ad4-846d-ffbf5619e370)

https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#dataset-locations
```
my-profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: abc-123
      dataset: my_dataset
      location: US # Optional, one of US or EU, or a regional location
```

### What problem does this solve?
If we have datasets across multiple locations in a Google Cloud project, we have to separate them by Lightdash location linked with a location. If the field of location isn't set, we can deal with datasets across multiple locations as BigQuery automatically detects the appropriate job location.
