### ISSUE TITLE
Disallow ${TABLE} and ${field} is `sql_on` field without specifying the table ${table.dimension}

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6682]
### Description

Currently we accept:

```yaml
joins:
  - join: table
    sql_on: ${field} = ${table.field}
```

But it's very confusing as to whether `${field}` should be a field on the base table or joined table. We should throw an error instead to prevent any surprises for the user.
