### ISSUE TITLE
Allow joins to be `always` joined

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#6693]
### Description

Joins are included in a query only if a query references a field from the joined table. 

However, when we using inner joins to restrict the data shown, it could be important to always join a table to the base table to filter results.

```yaml
joins:
  - join: other_table
    sql_on: ${base.id} = ${other_table.id}
    always: true
```

### Docs

Update the `tables` reference doc to include this.
