### ISSUE TITLE
validator table UI issues

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#6995]
### Description

1. Table heading has unnecessary bottom borders
2. After "views" there is unnecessary '.'
3. Content inside error column is not proportional
4. Last validated at should have a friendlier formatting
5. Delete icon is inconsistent. it should be ActionIcon with `X` icon

![CleanShot 2023-09-04 at 14 19 57@2x](https://github.com/lightdash/lightdash/assets/962095/b24eddd1-63c8-4860-959f-3126c9da6b0f)

**Comment by nimit9** [comment]
Hey @IrakliJani , I'd like to work on this

**Comment by ZeRego** [comment]
@nimit9 👍 go for it

**Comment by nimit9** [comment]
@ZeRego @IrakliJani How do I produce the errors? In my local setup, there are no errors when I'm running the validator

**Comment by nimit9** [comment]
@ZeRego @IrakliJani How do I produce the errors? When I'm running the validator on local, there are no errors

**Comment by ZeRego** [comment]
Good question! 
1. Go to `examples/full-jaffle-shop-demo/dbt/models/schema.yml` and delete 
```
      - name: order_date
        description: Date (UTC) that the order was placed
        meta:
          metrics:
            date_of_first_order:
              type: min
            date_of_most_recent_order:
              type: max
```
2. Go to the tables page and click `refresh dbt` 
3. Go to the validation page and see errors
