### ISSUE TITLE
Use the dbt artifacts of catalog to determine the default type of dimensions

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#7038]
### Description
If we declare only columnames without dimensions for Lightdash, the type of columns are string by default. For instance, if we have the subsequent schema property of a model, the data type of them is string by default. As Lightdash compiles a dbt project to deploy, we can take advantage of `catalog.json` to figure out the data types of columns.

```yaml
models:
  - name: orders
    columns:
      - name: ordered_at # timestamp
      - name: status. # string
```

We may also be able to use the data contract of the data type introduced at dbt 1.5 so that Lightdash determines the data type of columns without information of dimeisions.

```yaml
models:
  - name: orders
    columns:
      - name: ordered_at
        data_type: TIMESTAMP
      - name: status
```

### What problem does this solve?
One of the hassle points in Lightdash is that we have to declare the type of dimensions, specifically if the data type isn't string. If Lightdash determines the defaut data types of dimensions using `catalog.json` which contains data types of columns, we can more focus on annotate `meta` of columns which requires more tailered configurations.

**Comment by yu-iskw** [comment]
Let me write up extra context behind the issue as well as propose an example specification copatible with the current spec of Lightdash dimensions.

1. It would be good to take advantage of the official feature of dbt on data contract. We can manage the contract with a single feature in both of dbt and Lightdash.
2. We can leverage of community-based tools for dbt like dbt-osmosis. The tools enables us to get dbt schema properties mended like the `lightdash generate` command.


## No definition of a column
Lightdash doesn't interpret the column as a dimension. As the `created_at` comun isn't defined, Lightdash can't interpret it.

```yaml
  columns:
    - name: user_id
#   - name: created_at
```

## Only column name is defined
Lightdash can interpret the column as STRING by default as now. The `created_at` column is interpreted as STRING by Lightdash.

```yaml
  columns:
    - name: user_id
    - name: created_at
```

## Only column name is defined
Lightdash can interpret the column as STRING by default as now. Lightdash can interpret it as TIMESTAMP explicitly. Lightdash can also set the default values of settings like `time_intervals` to the TIMESTAMP data type.

```yaml
  columns:
    - name: user_id
    - name: created_at
      data_type: TIMESTAMP
```

## Override or use the current configuration manner

Lightdash can interpret the column as STRING by default as now. Lightdash can interpret it as TIMESTAMP explicitly. Lightdash can also set the default values of settings like `time_intervals` to the TIMESTAMP data type.

```yaml
  columns:
    - name: user_id
    - name: created_at
      data_type: TIMESTAMP
      meta:
        dimension:
          time_intervals: ['DAY', 'WEEK', 'MONTH']. #use the setting
```
