### ISSUE TITLE
I want to be able to specify values to appear first in the suggested filters list for a column

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7065]
### Description

In my .yml file, I want to specify suggested filter values for a column so they appear in the filter autocomplete dropdown — and optionally turn off the warehouse query entirely for expensive high-cardinality fields.

This is configured under a dimension's `meta` via a `filter_autocomplete` object. `values` is an **array of objects** (rather than plain strings) so we can attach more per-value configuration in the future (e.g. display labels, descriptions) without a breaking change.

```yaml
columns:
  - name: status
    meta:
      dimension:
        filter_autocomplete:
          values:                       # optional static list
            - value: 'active'
            - value: 'churned'
            - value: 'trial'
          fetch_from_warehouse: false   # optional, default true
```

### Behaviour

| `values` | `fetch_from_warehouse` | Filter dropdown behaviour |
| -- | -- | -- |
| — | `true` (default / no config) | Unchanged: query warehouse on open + on search |
| `[list]` | `true` | Show static list on open; query warehouse only when the user types a search |
| — | `false` | Never queries warehouse; free-text entry only |
| `[list]` | `false` | Show static list + free-text entry; never queries warehouse |

### Acceptance criteria

- [ ] There's a way to define a set of suggested filter values for a column in the .yml file, under a dimension's `meta` via `filter_autocomplete.values` — an array of `{ value: string }` objects.
- [ ] By default, if there are no values entered in the filter and you click to autocomplete, it suggests the configured `values`.
- [ ] `filter_autocomplete.fetch_from_warehouse: false` prevents the filter dropdown from issuing any warehouse value-search query (for expensive high-cardinality fields). Users can still type arbitrary values freely.
- [ ] If you start typing, matching configured values appear, then next-best matching values below.
- [ ] There is some indication that the values are `suggested values` in the autocomplete.

GitHub: [https://github.com/lightdash/lightdash/issues/23717](<https://github.com/lightdash/lightdash/issues/23717>)
