### ISSUE TITLE
`format` isn't applied to dimensions with custom SQL 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#7269]
### Description

If I calculate a dimension with a percentage in my yml (for a virtual column), I cannot seem to format it correctly.  If the column is stored in the database, this is not a problem. 

```
      - name: percentage_of_female_undergraduates
        meta:
          dimension:
            label: "Percentage of Female Undergrad"
            sql: ${num_female_undergraduates}::float / NULLIF(${num_undergraduates},0)
            format: 'percent'
            round: 2
```

![image](https://github.com/lightdash/lightdash/assets/31848148/845bc467-5406-4416-96c1-abff5dec4b53)
