### ISSUE TITLE
Support default values of filter(s) at table level or set required filter(s) 

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#7410]
### Description
We can define the `filters` property of a metric as of this writing. It would be good to support default values of filters at table level. We can change the default values as regular filters. They aren't fixed values.

### What problem does this solve?
BigQuery enables us to set an option, called `require_partition_filter`, to enforce to use condition(s) to narrow down partitions. We can avoid to query to large amount data across partitions. As we can't understand the column with `required_partition_filter`, required partition filters on Lightdash would be more intuitive for data consumers.

```
# created_at in the last 7 days is set by default
models:
  - name: Sales
    meta:
      filters:
        - created_at: "<= 7 days"
```

### Links
- https://cloud.google.com/bigquery/docs/managing-partitioned-tables#require-filter
