### ISSUE TITLE
On explore, my joins are not ordered by label

### ISSUE THREAD

**Issue by rephus** [lightdash/lightdash#7489]
### Description

I have this join yml: 

```
  - name: payments
    description: This table has information about individual payments
    meta:
      joins:
        - join: orders
          alias: orders
          label: my orders
          sql_on: ${orders.order_id} = ${payments.order_id}
        - join: customers
          label: win customers 
          alias: customers
          sql_on: ${customers.customer_id} = ${orders.customer_id}
```

According to this code, the explores should be sorted by label https://github.com/lightdash/lightdash/blob/92d3f1654a1cb07899d43d62ab0b191c5c473c8a/packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx#L112

However, I got the same old order (customers first, then orders) 

![image](https://github.com/lightdash/lightdash/assets/1983672/a5bf983e-9891-4b9a-a5e4-c3f684d6c5bf)

![image](https://github.com/lightdash/lightdash/assets/1983672/45e06a0d-07eb-49c5-af7c-e903d53b24fa)
