### ISSUE TITLE
Metric seems to be broken based on the length of the identifier

### ISSUE THREAD

**Issue by Kobold** [lightdash/lightdash#7759]
### Description

I created a few metrics and they seemed to conk out even though the underlying SQL is correct. After messing around, I discovered that it seems to fail once an identifier is too long. It would be ideal if Lightdash did either or both of:

- Not fail for reasonable length identifiers.
- Warn that metric won't work, explain why, and how to fix it. (in CLI, web UI, or both).

### To Reproduce

Here's the start of the model yaml with metrics declarations. The two metrics are the same, just with different names.

```yaml
version: 2
models:
  - name: lightdash__historical_analysis_date_range
    meta:
      label: Historical Analysis for Advisors Explore
      metrics:
        ...
        count_advisor_history_user_ids:
          type: count_distinct
          sql: ${lightdash__historical_advisor.history_user_id}
        cahu:
          type: count_distinct
          sql: ${lightdash__historical_advisor.history_user_id}
```

Here's what shows up in the web UI:

<img width="1427" alt="image" src="https://github.com/lightdash/lightdash/assets/36694/866d8c6c-1d13-4e76-aaf8-0c325de6d357">

The actual underlying SQL query runs just fine:

_Edit: this was accidentally the same screenshot as above. That query above when run in the SQL runner produces the same value (2,751) for both columns._

### App Version

Web UI: 0.832.2
CLI: 0.837.0
