### ISSUE TITLE
Cannot create a new project via CLI

### ISSUE THREAD

**Issue by wasd171** [lightdash/lightdash#7939]
### Description

I have the following `profiles.yml` file:
```
config:
  send_anonymous_usage_stats: false
  use_colors: true

careerlunch:
  target: dev
  outputs:
    dev: &dev-config
      type: postgres
      threads: 8
      # We add a default env value for production target
      schema: "dbt_{{ env_var('DBT_ACTOR', '') }}"
      host: "{{ env_var('DBT_POSTGRESQL_HOST') }}"
      port: "{{ env_var('DBT_POSTGRESQL_PORT') | as_number }}"
      dbname: "{{ env_var('DBT_POSTGRESQL_DATABASE') }}"
      user: "{{ env_var('DBT_POSTGRESQL_USER') }}"
      password: ''
      sslmode: verify-full
      sslcert: "{{ env_var('DBT_POSTGRESQL_SSL_CERT') }}"
      sslkey: "{{ env_var('DBT_POSTGRESQL_SSL_KEY') }}"
      sslrootcert: "{{ env_var('DBT_POSTGRESQL_SSL_ROOT_CERT') }}"
    prod:
      <<: *dev-config
      schema: analytics

```

I am able to successfully run `dbt compile` when setting correct env variables. However, running `lightdash deploy --create --profiles-dir .` fails with `Postgres target requires a password: "password"` <- this is wrong, `password` might not be required when performing cert-based authentication. Problematic line is here: https://github.com/lightdash/lightdash/blob/cecb734bef26183c4909f8557006ae61ee5c4181/packages/cli/src/dbt/targets/postgres.ts#L100

OK, what would happen if I set `password: " "`? Then I will get the following error: `Error running postgres query: Error: self-signed certificate in certificate chain`. This happens because CLI code ignores SSL options apart from `sslmode`: https://github.com/lightdash/lightdash/blob/cecb734bef26183c4909f8557006ae61ee5c4181/packages/cli/src/dbt/targets/postgres.ts#L109-L121

Since `lightdash` CLI acts as a wrapper to the `dbt` cli, I would expect it to work with the same config files, which unfortunately is not the case

### App Version
`0.863.9`
