### ISSUE TITLE
Snowflake error when client_session_keep_alive is enabled

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#8034]
### Description

Dbt docs on snowflake profile https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup

Docs for `client_session_keep_alive` 
> If True, the snowflake client will keep connections for longer than the default 4 hours. This is helpful when particularly long-running queries are executing (> 4 hours). Default: False (see [note below](https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup#client_session_keep_alive))

Lightdash shouldn't have to handle queries that take longer than 4 hours. So we should discard this configuration.

### To Reproduce

Create a project in the CLI where the snowflake profile has `client_session_keep_alive: True`
eg: 
```
jaffle_shop:
  target: jaffle
  outputs:
    jaffle:
      type: snowflake
      account: ...
      user: ...
      password: ...
      role: ...
      database: ...
      warehouse: ...
      schema: jaffle
      client_session_keep_alive: True
```

The CLI will return the error:
```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "callback" argument must be of type function. Received undefined
    at setInterval (node:timers:212:3)
    at Object.callback (/usr/app/node_modules/snowflake-sdk/lib/connection/connection.js:194:26)
    at Timeout.requestCallback (/usr/app/node_modules/snowflake-sdk/lib/services/sf.js:1231:23)
    at Object.callback (/usr/app/node_modules/snowflake-sdk/lib/services/sf.js:699:43)
    at /usr/app/node_modules/snowflake-sdk/lib/http/base.js:136:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### App Version

0.869.0
