### ISSUE TITLE
Allow additional aggregate metrics

### ISSUE THREAD

**Issue by gordonkjlee** [lightdash/lightdash#8051]
### Description
Lightdash metrics currently supports a number of standard aggregate functions (sum, count, etc.) but there may be use cases where custom aggregated metrics need to be used.

The easiest way is probably to allow a custom aggregate function to be used in the `SQL` key.

### What problem does this solve?
An example is MAU calculation where for performance reason I may I want to use `approx_count_distinct` for performance reasons. However, this does not appear to be currently supported, e.g. the following would not work.

```
columns:
    - name: user_id
        meta:
          dimension:
            type: string
            label: 'User Identifier'
            format: 'id'
          metrics:
            mau_metric:
              label: MAU
              type: number
              description: "Monthly Active Users"
              sql: "approx_count_distinct(${user_id})"
              round: 0
```

I can also imagine other aggregate functions being useful for other purposes, e.g. `mode`, `stddev`, etc
