### ISSUE TITLE
Column totals not working for number type with a percent format and rounding. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8100]
### Description

The column totals don't seem to be working for a metric  that is:

- a number type (number types seem to be working fine, so I don't think that's the issue)
- that's rounded (I'm not sure about this one? Maybe this is the issue?)
- and has a % formatting (I _**think**_ we fixed this, but maybe it's still a problem). 

Slack thread here: https://lightdash.slack.com/archives/C053ESBT36V/p1701087594028229?thread_ts=1700575263.292249&cid=C053ESBT36V

**Comment by IrakliJani** [comment]
@TuringLovesDeathMetal can't reproduce this

I tried this in the yml to mimic div0 from snowflake

```yml
              type: number
              format: percent
              round: 2
              sql: ${total_completed_order_amount} / NULLIF(${total_order_amount}, 0)

```
