### ISSUE TITLE
Headway update + docs on hidden joined tables

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8118]
Add this context:
Based on the features released in this thread, we have recommendations on how to manage your dbt yml.
Tag the models that need to be compiled for Lightdash with lightdash and tag the models that you want users to explore with lightdash-explore .
eg:
```
models:

    users:
      +tags:
        - "lightdash"
        - "lightdash-explore"

    hidden_join_model:
      +tags:
        - "lightdash"
 ```

When deploying lightdash via the CLI you should use the dbt selector -s lightdash to make sure we don't compile unnecessary models.
In the [project table settings](https://docs.lightdash.com/guides/adding-tables-to-lightdash#configuring-which-tables-appear-in-your-lightdash-project), filter by lightdash-explore so all the intermediary joins are hidden and users have a small and curated list of models then can explore from.
