### ISSUE TITLE
Ability to declare a join in YAML, including all fields except those specifically excluded

### ISSUE THREAD

**Issue by IrakliJani** [lightdash/lightdash#8180]
### Description

Implement a way to exclude certain join fields directly within the model .yml file. This feature would enable users to specify which fields should not be included in a join, rather than listing all the fields to be included

Right now we have `fields` property to specify desired fields. but once you want to exclude something - you have to specify all the fields.

```yml
- join: web_sessions
  sql_on: ${web_sessions.user_id} = ${users.user_id}
  fields: [user_id, email, name]
```

maybe a `ignore_fields` property?

think of the ways how it will work with existing `fields` property
