### ISSUE TITLE
Support multiple values in required_attributes

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#8464]
### Description

https://docs.lightdash.com/references/user-attributes#2-column-filtering-with-required_attributes

When using user attributes for column filtering I want to allow multiple values for the same attribute. 

eg: group can be A or B

```
dimension:
  ...
  required_attributes: 
    group: ["a", "b"]
```

### What problem does this solve?

Since a user can only have 1 value per user attribute it is easier to update required_attributes rules to support more values.
Otherwise, we need to do user attribute gymnastics each time we have a new value.
