### ISSUE TITLE
I want to have `required attributes` to limit access to certain metrics. 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8472]
### Description

Right now, I can limit access to dimensions, and certain rows in my tables, but I can't limit access to metrics for certain groups. 

This is an issue because, let's say I hide `revenue` as a dimension from a group of users using `required_attributes`, but I have a metric called `total_revenue` (which is just the `sum` of `revenue`), there's no way for me to hide the `total revenue` metric from these users as well. 

So, they still have access to the dimension (in a way), but just its aggregated form. 

I want to be able to limit access to metrics the same way I can for dimensions. 

### Acceptance criteria

- [ ] There is a way to use required attributes for metrics
- [ ] The format should be the same as with dimensions:
```yaml
columns: 
  - name: 
    description: User name
  - salary: 
    description: User salary 
    meta: 
      dimension:
        required_attributes:
          is_admin: "true"
      metrics:
        total_salary: 
          type: sum
          required_attributes: 
            is_admin: "true" 
            team_name: ["HR", "C-Suite"]
```
- [ ] Update docs on User attributes to include section on metric-restriction using user attributes (here: https://docs.lightdash.com/references/user-attributes#using-user-attributes-in-lightdash)
