### ISSUE TITLE
Give models user-friendly display names

### ISSUE THREAD

**Issue by owlas** [lightdash/lightdash#857]
Explores in Lightdash are named after the dbt models that they are derived from.

The problem with this is that the dbt models are usually named to be familiar to the data specialists. It would be great if we could optionally specify a display name that is more easily understood.

I imagine:

```yaml
models:
  - name: confusing_model_name
    meta:
      displayName: Priority customers
...
```
