### ISSUE TITLE
Enable to generate dbt exposures for dashboards and support required APIs

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/lightdash#8620]
### Description

I want to generate dbt exposures for dashboards, as the type of a dbt exposure can be one of dashboard, notebook, analysis, ml and application. 

https://docs.getdbt.com/reference/exposure-properties

### What problem does this solve?

It would be more natural to create dbt exposures for Lightdash dashboards. To do so, I want to enhance the subsequent two approaches.

1. We can improve the `GetDbtExposures` API to generate the expected outcome as below for a `lightdash generate-exposures` command.
2. We can improve APIs for Lightdash users to create their own custom dbt exposures. The enhancement would be useful for advanced users who want to generate dbt exposures with their own format. For instance, as far as I know, an API to get information of saved charts in a dashboard isn't implemented.

#### Lightdash project example
We assume the subsequent Lightdash project to generate dbt exposures.

Please correct me, if the relationships are wrong. There are two dashboards in the space `Space A`. One is `Dashboard A` and the other is `Dashboard B`. Each dashboard contains saved charts. Each saved chart derives from a explore. An explore is composed of more than one table due to table join.

![image](https://github.com/lightdash/lightdash/assets/1523515/cc1cfdc5-6012-4305-a3c3-6b802331d67e)

#### Expected data lineage on dbt-docs
The data lineage on dbt-docs looks like below. A Lightdash dashboard is linked with used dbt models in saved charts.

![image](https://github.com/lightdash/lightdash/assets/1523515/a4a7a15d-d09d-425b-9c77-0f1f1fbfcce8)

The expected dbt exposure YAML file can be the subsequent code block.

```yaml
version: 2
exposures:
  - name: "${dashboard_a}"  # The ID of Dashboard A
    type: dashboard
    owner:
      name: xxx
      email: xxx@xxx.com
    label: Dashboard A
    description: This is a dashboard.
    url: >-
      https://app.lightdash.cloud/projects/xxxxxxxxx/dashboards/xxxxx/view
    tags:
      - lightdash
    depends_on:
      - table_a
      - table_b
  - name: "${dashboard_b}"  # The ID of Dashboard B
    type: dashboard
    owner:
      name: yyy
      email: yyy@xxx.com
    label: Dashboard B
    description: This is a dashboard.
    url: >-
      https://app.lightdash.cloud/projects/xxxxxxxxx/dashboards/yyyyy/view
    tags:
      - lightdash
    depends_on:
      - table_b
      - table_c
      - table_d
      - table_d_dash
```
