### ISSUE TITLE
Validator error messages are misleading in some cases

### ISSUE THREAD

**Issue by magnew** [lightdash/lightdash#8635]
### Description

In some cases the validator returns a misleading generic error message. `matches no dimension` when we could be helping users understand what went wrong better. Two cases that have been mentioned in support are:

1. Using `average` instead of `number` in the `yml` file returns `matches no dimension`. This would be more helpful if it pointed out the **types** don't match. 
2. Forgetting to add `sql: ${dimension}` filter but directly referencing another metric as below returns `matches no dimension`. It could point out that what is missing is the **dimension reference**
```
my_metric_name:
              type: sum
              label: Direct Opens
metrics:
my_second_metric:
              type: number
              label: Open Rate
              format: percent
              sql: |
                div0( zeroifnull( ${my_metric_name} ),${m_totals} )
  ```
