### ISSUE TITLE
You should be able to reference doc blocks in Lightdash metric descriptions

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8858]
### Description

Right now, if I try to reference a doc block in a metric description, like this:

```yaml
version: 2
models:
  - name: users
    columns:
      - name: user_id
        description: "{{doc(\"user_id\")}}"
        meta:
          metrics:
            count_user_ids:
              type: count
              description: "{{doc(\"user_id\")}}" # this breaks
```

This will return an error: `Could not render {{ doc("user_id") }}: 'doc' is undefined`
