### ISSUE TITLE
string dimension types are being formatted as numbers in the UI

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8869]
### Description

```yaml
   columns:
      - name: id
        description: Unique ID for the pull request
        meta:
          dimension:
            type: string
```

<img width="309" alt="image" src="https://github.com/lightdash/lightdash/assets/31848148/67a88115-9416-426e-a531-b11f314deeb7">

^These are appearing like strings now with commas (instead of numbers, like they used to be). This means that IDs are appearing weridly in the UI
