### ISSUE TITLE
dimensions defined using custom SQL should have suggested filter values

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#8912]
### Description

Right now, if I have a dimension that's defined using custom SQL or any additional dimensions, then I dont' get any suggestions in the filter autocomplete. 

e.g. 
```yaml
name: status
  meta:
    dimension:
      sql: IF(${TABLE}.status = TRUE, 'completed', 'in progress')
```

The `status` field in Lightdash would have no autocomplete suggestions as a filter (since it's not just querying the data in the underlying table, it's applying some custom SQL to it).
