### ISSUE TITLE
Unable to connect to external DB

### ISSUE THREAD

**Issue by tom10271** [lightdash/lightdash#9235]
### Description

Unable to connect to external DB

### To Reproduce
values.yml
```yml
# values.yaml

# Disable the internal database
postgresql:
    enabled: false

# Configure Lightdash to use an external database
externalDatabase:
    host: my-rds-confirmed-connectable-within-my-eks-cluster.crjxigilzqkd.us-west-2.rds.amazonaws.com
    port: 5432
    user: lightdash_app
    password: password
    database: lightdash

```

2. Run `helm install lightdash lightdash/lightdash -n lightdash -f values.yaml`

### App Version
Latest version available via Helm

We have tried to directly override CONNECTION in `/usr/app/packages/backend/dist/database/knexfile.js` to `'postgresql://lightdash_app:pwdpwd123123@my-postgres.crjxigilzqkd.us-west-2.rds.amazonaws.com:5432/lightdash'`

When we run `/usr/bin/prod-entrypoint.sh`, the following error returns while `10.0.103.62` is actually the pod IP

```
no pg_hba.conf entry for host "10.0.103.62", user "lightdash_app", database "lightdash", no encryption
error: no pg_hba.conf entry for host "10.0.103.62", user "lightdash_app", database "lightdash", no encryption
    at Parser.parseErrorMessage (/usr/app/node_modules/pg/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/app/node_modules/pg/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/app/node_modules/pg/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/app/node_modules/pg/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```
