### ISSUE TITLE
Lightdash YML generation overrides quote settings

### ISSUE THREAD

**Issue by fev4** [lightdash/lightdash#9308]
### Description

Hey there,

When I ran `lightdash dbt run -s model_with_quoted_cols`, the schema went from this:

```
version: 2
models:
  - name: offline_gads_conversions
    columns:
      - name: "Google Click ID"
        quote: true
        description: ""
        meta:
          dimension:
            type: string
      - name: "Conversion Name"
        quote: true
        description: ""
        meta:
          dimension:
            type: string
      - name: "Conversion Time"
        quote: true
        description: ""
        meta:
          dimension:
            type: timestamp
      - name: "Conversion Value"
        quote: true
        description: ""
        meta:
          dimension:
            type: number
      - name: "Conversion Currency"
        quote: true
        description: ""
        meta:
          dimension:
            type: string
```

To this:
```
version: 2
models:
  - name: offline_gads_conversions
    columns:
      - name: google click id
        description: ""
        meta:
          dimension:
            type: string
      - name: conversion name
        description: ""
        meta:
          dimension:
            type: string
      - name: conversion time
        description: ""
        meta:
          dimension:
            type: timestamp
      - name: conversion value
        description: ""
        meta:
          dimension:
            type: number
      - name: conversion currency
        description: ""
        meta:
          dimension:
            type: string
```

It removed the capitalization, the quotes, and the quote settings. Further work with the model would end up breaking because the quote setting is needed to generate the correct compilation for the DB.

### To Reproduce

Create an SQL file with dummy data:

```
select
  'abc123' AS "Google Click ID",
  'Purchase' AS "Conversion Name",
  '2023-03-09 10:30:00' AS "Conversion Time",
  100.00 AS "Conversion Value",
  'USD' AS "Conversion Currency"

union all

select
  'def456' AS "Google Click ID",
  'Sign Up' AS "Conversion Name",
  '2023-03-08 15:45:00' AS "Conversion Time",
  0.00 AS "Conversion Value",
  'USD' AS "Conversion Currency"

union all

select
  'ghi789' AS "Google Click ID",
  'Download' AS "Conversion Name",
  '2023-03-07 09:15:00' AS "Conversion Time",
  0.00 AS "Conversion Value",
  'USD' AS "Conversion Currency"
```

Then use the same YAML file as the initial state.
Then run `lightdash dbt run -s <name_of_sql_file_created>`

Which in turn should generate the output pointed at the beginning.

### App Version

0.1027.3

### Context
Google Ads requires this column format for offline conversion uploads.

---

That's it. Please let me know if there's any other info I can help with.
