### ISSUE TITLE
If I use `data_type` in my dbt model, this should be used by Lightdash as well

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9535]
### Description

You can actually define the `data_type` in dbt like this: 

```yaml
models:
  - name: dim_customers
    config:
      materialized: table
      contract:
        enforced: true
    columns:
      - name: customer_id
        data_type: int
        constraints:
          - type: not_null
      - name: customer_name
        data_type: string
      - name: non_integer
        data_type: numeric(38,3)
```

But, Lightdash doesn't actually pick this up. I had a user confused by this because Lightdash was showing a column as a string, when actually it was a number (and they'd specified that it was a number in their dbt .yml using hte `data_type` parameter). 

We should use data_type in Lightdash. 

Here's more info on data types in dbt:
https://docs.getdbt.com/reference/resource-configs/contract

### Behaviour

I'd expect the interpretation of data types in Lightdash to go like this:

1. Check the schema in the data warehouse for the data type (if yes, take this - continue to 2/3)
2. Check if there is a `data type` defined in dbt (if yes, use this instead of (1) - continue to 3)
3. check if there is a `type` defined in Lightdash meta  (if yes, use this instead of (2))
