### ISSUE TITLE
Table join aliases not resolved correctly during project compilation

### ISSUE THREAD

**Issue by filp** [lightdash/lightdash#9726]
### Description

Defining model aliases leads to incorrect join alias resolution issues across table boundaries, and in cases of self-referential joins on the same model where the alias is first defined.

### Steps to Reproduce the Bug or Issue

Define an alias on a join:

```yaml

    - name: orders
      description: |
          This table has basic information about orders, as well as some derived
          facts based on payments

          {{ doc("orders_status") }}
      meta:
          joins:
              - join: customers
                alias: foo # <--
                sql_on: ${customers.customer_id} = ${orders.customer_id}
```

Define a metric using this alias on this same model:

```yaml
            meta:
                metrics:
                    first_name_count:
                        type: count_distinct
                        sql: ${foo.first_name} IS NOT NULL
```

The above works fine, but causes models joining this one to fail to compile, because (in the example above) the `payments` compilation is unaware of the join alias.

```
- SUCCESS> users
- ERROR> payments : Model "orders" has a dimension reference: ${foo.first_name} which matches no dimension
- SUCCESS> membership
- SUCCESS> plan
- SUCCESS> generated_b
- SUCCESS> generated_a
- SUCCESS> events
- SUCCESS> stg_customers
- SUCCESS> stg_payments
- SUCCESS> stg_orders
- SUCCESS> customers
- SUCCESS> orders
```

### Cloud or self-hosting

None
