### ISSUE TITLE
Enforce docker image platform

### ISSUE THREAD

**Issue by ZeRego** [lightdash/lightdash#9968]
### Description

slack thread: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1714659247150579

We need to update or docker compose to have the platform

```
services:
  lightdash:
    platform: linux/amd64
    image: lightdash/lightdash:latest
```

### Steps to Reproduce the Bug or Issue

```
Using default tag: latest
latest: Pulling from lightdash/lightdash
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### Cloud or self-hosting

None
