### ISSUE TITLE
I want totals to appear in my pivot tables for all metric types 

### ISSUE THREAD

**Issue by TuringLovesDeathMetal** [lightdash/lightdash#9981]
### Description

Today, totals only appear for `sum` and `count` metric types in pivot tables.

I want totals to be calculated for all of my metric types (e.g. `count distinct`, `average`, etc.)

This includes both column totals and row totals

**Comment by TuringLovesDeathMetal** [comment]
Is this related to #2907 ?

**Comment by rephus** [comment]
For context, we don't calculate totals on pivot tables for metric type `number`, because the `sum` of numbers is not a correct total. 

Let's take this example: 

I have a metric which is a type:number calculated from `sums`

```
      - name: amount
        description: Total amount (AUD) of the individual payment
        meta:
          metrics:
            total_revenue:
              type: sum
              description: Sum of all payments
            total_cost:
                type: number
                sql: ${total_revenue} - 10
            total_percent_profit: 
                type: number
                sql: 100 * ${total_revenue}/${total_cost}
```

WHen I calculate totals in a non-pivot table, the result is correct, we calculate this on a special backend endpoint, by grouping the right columns.

![image](https://github.com/user-attachments/assets/d4cb8a4c-cef9-4b67-a7e2-3079bec76925)

When I pivot the table, the frontend is `aggregating` all the rows, to calculate the total, (because we allowed NUMBER on `isSummable` function) , the total result is wrong.

![image](https://github.com/user-attachments/assets/8592655a-fccc-44aa-bd9c-8bcced03f6a7)

FOr this use case, we could `manually` calculate the total, by running the `100 * ${total_revenue}/${total_cost}` operation on the `total of the individual metrics`, like: 

> 100 * (994.16 /	854.16) = 116

However, the main issue is that in the `frontend`, this total_revenue and total_cost might not be present in the result of the query, so we'll have to move this calculation to the backend somehow, per dimension pivot, which is not an easy thing to do. 

So we decided to temporarily remove this total calculation from number types
